/**********************************************************
 * This file is generated by 20-sim C++ Code Generator
 *
 *  file:  interaction_control.cpp
 *  subm:  interaction_control
 *  model: ControlYoubotArmInteraction_v2
 *  expmt: ControlYoubotArmInteraction_v2
 *  date:  April 12, 2011
 *  time:  4:52:06 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* Standard include files */
#include <stdio.h>
#include <math.h>
#include <stdexcept>

/* 20-sim include files */
#include "interaction_control.h"

	/* this PRIVATE function sets the input variables from the input vector */
void interaction_control::CopyInputsToVariables (XXDouble *u)
{
	/* copy the input vector to the input variables */
	m_V[467] = u[0];		/* joints.f */
	m_V[468] = u[1];
	m_V[469] = u[2];
	m_V[470] = u[3];
	m_V[471] = u[4];
	m_V[479] = u[5];		/* Linkdim */
	m_V[480] = u[6];
	m_V[481] = u[7];
	m_V[482] = u[8];
	m_V[483] = u[9];
	m_V[484] = u[10];
	m_V[485] = u[11];
	m_V[486] = u[12];
	m_V[487] = u[13];
	m_V[488] = u[14];
	m_V[489] = u[15];
	m_V[490] = u[16];
	m_V[491] = u[17];
	m_V[492] = u[18];
	m_V[493] = u[19];
	m_V[494] = u[20];
	m_V[495] = u[21];
	m_V[496] = u[22];
	m_V[497] = u[23];		/* q */
	m_V[498] = u[24];
	m_V[499] = u[25];
	m_V[500] = u[26];
	m_V[501] = u[27];
	m_V[472] = u[28];		/* xyzQuart */
	m_V[473] = u[29];
	m_V[474] = u[30];
	m_V[475] = u[31];
	m_V[476] = u[32];
	m_V[477] = u[33];
	m_V[478] = u[34];

}

/* this PRIVATE function uses the output variables to fill the output vector */
void interaction_control::CopyVariablesToOutputs (XXDouble *y)
{
	/* copy the output variables to the output vector */
	y[0] = 	m_V[462];		/* joints.e */
	y[1] = 	m_V[463];
	y[2] = 	m_V[464];
	y[3] = 	m_V[465];
	y[4] = 	m_V[466];
	y[5] = 	m_V[502];		/* output */
	y[6] = 	m_V[503];
	y[7] = 	m_V[504];
	y[8] = 	m_V[505];
	y[9] = 	m_V[506];
	y[10] = 	m_V[507];
	y[11] = 	m_V[508];
	y[12] = 	m_V[509];
	y[13] = 	m_V[510];
	y[14] = 	m_V[511];
	y[15] = 	m_V[512];
	y[16] = 	m_V[513];
	y[17] = 	m_V[514];
	y[18] = 	m_V[515];
	y[19] = 	m_V[516];
	y[20] = 	m_V[517];

}
void interaction_control::initVarNames(void){
	std::string m_constant_names[15+1] = {
			"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	""

	};
	std::string m_parameter_names[2+1] = {
			"CtipControl1\\CtipControl",
	"R\\controlDamping"

	};
	std::string m_initial_value_names[0+1] = {
			NULL
	};
	std::string m_variable_names[518+1] = {
			"CalculateJ\\controllableJ[1,1]",
	"CalculateJ\\controllableJ[1,2]",
	"CalculateJ\\controllableJ[1,3]",
	"CalculateJ\\controllableJ[1,4]",
	"CalculateJ\\controllableJ[1,5]",
	"CalculateJ\\controllableJ[2,1]",
	"CalculateJ\\controllableJ[2,2]",
	"CalculateJ\\controllableJ[2,3]",
	"CalculateJ\\controllableJ[2,4]",
	"CalculateJ\\controllableJ[2,5]",
	"CalculateJ\\controllableJ[3,1]",
	"CalculateJ\\controllableJ[3,2]",
	"CalculateJ\\controllableJ[3,3]",
	"CalculateJ\\controllableJ[3,4]",
	"CalculateJ\\controllableJ[3,5]",
	"CalculateJ\\controllableJ[4,1]",
	"CalculateJ\\controllableJ[4,2]",
	"CalculateJ\\controllableJ[4,3]",
	"CalculateJ\\controllableJ[4,4]",
	"CalculateJ\\controllableJ[4,5]",
	"CalculateJ\\controllableJ[5,1]",
	"CalculateJ\\controllableJ[5,2]",
	"CalculateJ\\controllableJ[5,3]",
	"CalculateJ\\controllableJ[5,4]",
	"CalculateJ\\controllableJ[5,5]",
	"CalculateJ\\controllableJ[6,1]",
	"CalculateJ\\controllableJ[6,2]",
	"CalculateJ\\controllableJ[6,3]",
	"CalculateJ\\controllableJ[6,4]",
	"CalculateJ\\controllableJ[6,5]",
	"CalculateJ\\Htip0[1,1]",
	"CalculateJ\\Htip0[1,2]",
	"CalculateJ\\Htip0[1,3]",
	"CalculateJ\\Htip0[1,4]",
	"CalculateJ\\Htip0[2,1]",
	"CalculateJ\\Htip0[2,2]",
	"CalculateJ\\Htip0[2,3]",
	"CalculateJ\\Htip0[2,4]",
	"CalculateJ\\Htip0[3,1]",
	"CalculateJ\\Htip0[3,2]",
	"CalculateJ\\Htip0[3,3]",
	"CalculateJ\\Htip0[3,4]",
	"CalculateJ\\Htip0[4,1]",
	"CalculateJ\\Htip0[4,2]",
	"CalculateJ\\Htip0[4,3]",
	"CalculateJ\\Htip0[4,4]",
	"CalculateJ\\Linkdim[1,1]",
	"CalculateJ\\Linkdim[1,2]",
	"CalculateJ\\Linkdim[1,3]",
	"CalculateJ\\Linkdim[1,4]",
	"CalculateJ\\Linkdim[1,5]",
	"CalculateJ\\Linkdim[1,6]",
	"CalculateJ\\Linkdim[2,1]",
	"CalculateJ\\Linkdim[2,2]",
	"CalculateJ\\Linkdim[2,3]",
	"CalculateJ\\Linkdim[2,4]",
	"CalculateJ\\Linkdim[2,5]",
	"CalculateJ\\Linkdim[2,6]",
	"CalculateJ\\Linkdim[3,1]",
	"CalculateJ\\Linkdim[3,2]",
	"CalculateJ\\Linkdim[3,3]",
	"CalculateJ\\Linkdim[3,4]",
	"CalculateJ\\Linkdim[3,5]",
	"CalculateJ\\Linkdim[3,6]",
	"CalculateJ\\uTr1refref[1]",
	"CalculateJ\\uTr1refref[2]",
	"CalculateJ\\uTr1refref[3]",
	"CalculateJ\\uTr1refref[4]",
	"CalculateJ\\uTr1refref[5]",
	"CalculateJ\\uTr1refref[6]",
	"CalculateJ\\uTr211[1]",
	"CalculateJ\\uTr211[2]",
	"CalculateJ\\uTr211[3]",
	"CalculateJ\\uTr211[4]",
	"CalculateJ\\uTr211[5]",
	"CalculateJ\\uTr211[6]",
	"CalculateJ\\uTr322[1]",
	"CalculateJ\\uTr322[2]",
	"CalculateJ\\uTr322[3]",
	"CalculateJ\\uTr322[4]",
	"CalculateJ\\uTr322[5]",
	"CalculateJ\\uTr322[6]",
	"CalculateJ\\uTr433[1]",
	"CalculateJ\\uTr433[2]",
	"CalculateJ\\uTr433[3]",
	"CalculateJ\\uTr433[4]",
	"CalculateJ\\uTr433[5]",
	"CalculateJ\\uTr433[6]",
	"CalculateJ\\uTr544[1]",
	"CalculateJ\\uTr544[2]",
	"CalculateJ\\uTr544[3]",
	"CalculateJ\\uTr544[4]",
	"CalculateJ\\uTr544[5]",
	"CalculateJ\\uTr544[6]",
	"CalculateJ\\R1ref[1,1]",
	"CalculateJ\\R1ref[1,2]",
	"CalculateJ\\R1ref[1,3]",
	"CalculateJ\\R1ref[2,1]",
	"CalculateJ\\R1ref[2,2]",
	"CalculateJ\\R1ref[2,3]",
	"CalculateJ\\R1ref[3,1]",
	"CalculateJ\\R1ref[3,2]",
	"CalculateJ\\R1ref[3,3]",
	"CalculateJ\\R21[1,1]",
	"CalculateJ\\R21[1,2]",
	"CalculateJ\\R21[1,3]",
	"CalculateJ\\R21[2,1]",
	"CalculateJ\\R21[2,2]",
	"CalculateJ\\R21[2,3]",
	"CalculateJ\\R21[3,1]",
	"CalculateJ\\R21[3,2]",
	"CalculateJ\\R21[3,3]",
	"CalculateJ\\R32[1,1]",
	"CalculateJ\\R32[1,2]",
	"CalculateJ\\R32[1,3]",
	"CalculateJ\\R32[2,1]",
	"CalculateJ\\R32[2,2]",
	"CalculateJ\\R32[2,3]",
	"CalculateJ\\R32[3,1]",
	"CalculateJ\\R32[3,2]",
	"CalculateJ\\R32[3,3]",
	"CalculateJ\\R43[1,1]",
	"CalculateJ\\R43[1,2]",
	"CalculateJ\\R43[1,3]",
	"CalculateJ\\R43[2,1]",
	"CalculateJ\\R43[2,2]",
	"CalculateJ\\R43[2,3]",
	"CalculateJ\\R43[3,1]",
	"CalculateJ\\R43[3,2]",
	"CalculateJ\\R43[3,3]",
	"CalculateJ\\R54[1,1]",
	"CalculateJ\\R54[1,2]",
	"CalculateJ\\R54[1,3]",
	"CalculateJ\\R54[2,1]",
	"CalculateJ\\R54[2,2]",
	"CalculateJ\\R54[2,3]",
	"CalculateJ\\R54[3,1]",
	"CalculateJ\\R54[3,2]",
	"CalculateJ\\R54[3,3]",
	"CalculateJ\\Rtip5[1,1]",
	"CalculateJ\\Rtip5[1,2]",
	"CalculateJ\\Rtip5[1,3]",
	"CalculateJ\\Rtip5[2,1]",
	"CalculateJ\\Rtip5[2,2]",
	"CalculateJ\\Rtip5[2,3]",
	"CalculateJ\\Rtip5[3,1]",
	"CalculateJ\\Rtip5[3,2]",
	"CalculateJ\\Rtip5[3,3]",
	"CalculateJ\\p1ref[1]",
	"CalculateJ\\p1ref[2]",
	"CalculateJ\\p1ref[3]",
	"CalculateJ\\p21[1]",
	"CalculateJ\\p21[2]",
	"CalculateJ\\p21[3]",
	"CalculateJ\\p32[1]",
	"CalculateJ\\p32[2]",
	"CalculateJ\\p32[3]",
	"CalculateJ\\p43[1]",
	"CalculateJ\\p43[2]",
	"CalculateJ\\p43[3]",
	"CalculateJ\\p54[1]",
	"CalculateJ\\p54[2]",
	"CalculateJ\\p54[3]",
	"CalculateJ\\ptip5[1]",
	"CalculateJ\\ptip5[2]",
	"CalculateJ\\ptip5[3]",
	"CalculateJ\\Href0[1,1]",
	"CalculateJ\\Href0[1,2]",
	"CalculateJ\\Href0[1,3]",
	"CalculateJ\\Href0[1,4]",
	"CalculateJ\\Href0[2,1]",
	"CalculateJ\\Href0[2,2]",
	"CalculateJ\\Href0[2,3]",
	"CalculateJ\\Href0[2,4]",
	"CalculateJ\\Href0[3,1]",
	"CalculateJ\\Href0[3,2]",
	"CalculateJ\\Href0[3,3]",
	"CalculateJ\\Href0[3,4]",
	"CalculateJ\\Href0[4,1]",
	"CalculateJ\\Href0[4,2]",
	"CalculateJ\\Href0[4,3]",
	"CalculateJ\\Href0[4,4]",
	"CalculateJ\\H1ref[1,1]",
	"CalculateJ\\H1ref[1,2]",
	"CalculateJ\\H1ref[1,3]",
	"CalculateJ\\H1ref[1,4]",
	"CalculateJ\\H1ref[2,1]",
	"CalculateJ\\H1ref[2,2]",
	"CalculateJ\\H1ref[2,3]",
	"CalculateJ\\H1ref[2,4]",
	"CalculateJ\\H1ref[3,1]",
	"CalculateJ\\H1ref[3,2]",
	"CalculateJ\\H1ref[3,3]",
	"CalculateJ\\H1ref[3,4]",
	"CalculateJ\\H1ref[4,1]",
	"CalculateJ\\H1ref[4,2]",
	"CalculateJ\\H1ref[4,3]",
	"CalculateJ\\H1ref[4,4]",
	"CalculateJ\\H21[1,1]",
	"CalculateJ\\H21[1,2]",
	"CalculateJ\\H21[1,3]",
	"CalculateJ\\H21[1,4]",
	"CalculateJ\\H21[2,1]",
	"CalculateJ\\H21[2,2]",
	"CalculateJ\\H21[2,3]",
	"CalculateJ\\H21[2,4]",
	"CalculateJ\\H21[3,1]",
	"CalculateJ\\H21[3,2]",
	"CalculateJ\\H21[3,3]",
	"CalculateJ\\H21[3,4]",
	"CalculateJ\\H21[4,1]",
	"CalculateJ\\H21[4,2]",
	"CalculateJ\\H21[4,3]",
	"CalculateJ\\H21[4,4]",
	"CalculateJ\\H32[1,1]",
	"CalculateJ\\H32[1,2]",
	"CalculateJ\\H32[1,3]",
	"CalculateJ\\H32[1,4]",
	"CalculateJ\\H32[2,1]",
	"CalculateJ\\H32[2,2]",
	"CalculateJ\\H32[2,3]",
	"CalculateJ\\H32[2,4]",
	"CalculateJ\\H32[3,1]",
	"CalculateJ\\H32[3,2]",
	"CalculateJ\\H32[3,3]",
	"CalculateJ\\H32[3,4]",
	"CalculateJ\\H32[4,1]",
	"CalculateJ\\H32[4,2]",
	"CalculateJ\\H32[4,3]",
	"CalculateJ\\H32[4,4]",
	"CalculateJ\\H43[1,1]",
	"CalculateJ\\H43[1,2]",
	"CalculateJ\\H43[1,3]",
	"CalculateJ\\H43[1,4]",
	"CalculateJ\\H43[2,1]",
	"CalculateJ\\H43[2,2]",
	"CalculateJ\\H43[2,3]",
	"CalculateJ\\H43[2,4]",
	"CalculateJ\\H43[3,1]",
	"CalculateJ\\H43[3,2]",
	"CalculateJ\\H43[3,3]",
	"CalculateJ\\H43[3,4]",
	"CalculateJ\\H43[4,1]",
	"CalculateJ\\H43[4,2]",
	"CalculateJ\\H43[4,3]",
	"CalculateJ\\H43[4,4]",
	"CalculateJ\\H54[1,1]",
	"CalculateJ\\H54[1,2]",
	"CalculateJ\\H54[1,3]",
	"CalculateJ\\H54[1,4]",
	"CalculateJ\\H54[2,1]",
	"CalculateJ\\H54[2,2]",
	"CalculateJ\\H54[2,3]",
	"CalculateJ\\H54[2,4]",
	"CalculateJ\\H54[3,1]",
	"CalculateJ\\H54[3,2]",
	"CalculateJ\\H54[3,3]",
	"CalculateJ\\H54[3,4]",
	"CalculateJ\\H54[4,1]",
	"CalculateJ\\H54[4,2]",
	"CalculateJ\\H54[4,3]",
	"CalculateJ\\H54[4,4]",
	"CalculateJ\\Htip5[1,1]",
	"CalculateJ\\Htip5[1,2]",
	"CalculateJ\\Htip5[1,3]",
	"CalculateJ\\Htip5[1,4]",
	"CalculateJ\\Htip5[2,1]",
	"CalculateJ\\Htip5[2,2]",
	"CalculateJ\\Htip5[2,3]",
	"CalculateJ\\Htip5[2,4]",
	"CalculateJ\\Htip5[3,1]",
	"CalculateJ\\Htip5[3,2]",
	"CalculateJ\\Htip5[3,3]",
	"CalculateJ\\Htip5[3,4]",
	"CalculateJ\\Htip5[4,1]",
	"CalculateJ\\Htip5[4,2]",
	"CalculateJ\\Htip5[4,3]",
	"CalculateJ\\Htip5[4,4]",
	"CalculateJ\\H10[1,1]",
	"CalculateJ\\H10[1,2]",
	"CalculateJ\\H10[1,3]",
	"CalculateJ\\H10[1,4]",
	"CalculateJ\\H10[2,1]",
	"CalculateJ\\H10[2,2]",
	"CalculateJ\\H10[2,3]",
	"CalculateJ\\H10[2,4]",
	"CalculateJ\\H10[3,1]",
	"CalculateJ\\H10[3,2]",
	"CalculateJ\\H10[3,3]",
	"CalculateJ\\H10[3,4]",
	"CalculateJ\\H10[4,1]",
	"CalculateJ\\H10[4,2]",
	"CalculateJ\\H10[4,3]",
	"CalculateJ\\H10[4,4]",
	"CalculateJ\\H20[1,1]",
	"CalculateJ\\H20[1,2]",
	"CalculateJ\\H20[1,3]",
	"CalculateJ\\H20[1,4]",
	"CalculateJ\\H20[2,1]",
	"CalculateJ\\H20[2,2]",
	"CalculateJ\\H20[2,3]",
	"CalculateJ\\H20[2,4]",
	"CalculateJ\\H20[3,1]",
	"CalculateJ\\H20[3,2]",
	"CalculateJ\\H20[3,3]",
	"CalculateJ\\H20[3,4]",
	"CalculateJ\\H20[4,1]",
	"CalculateJ\\H20[4,2]",
	"CalculateJ\\H20[4,3]",
	"CalculateJ\\H20[4,4]",
	"CalculateJ\\H30[1,1]",
	"CalculateJ\\H30[1,2]",
	"CalculateJ\\H30[1,3]",
	"CalculateJ\\H30[1,4]",
	"CalculateJ\\H30[2,1]",
	"CalculateJ\\H30[2,2]",
	"CalculateJ\\H30[2,3]",
	"CalculateJ\\H30[2,4]",
	"CalculateJ\\H30[3,1]",
	"CalculateJ\\H30[3,2]",
	"CalculateJ\\H30[3,3]",
	"CalculateJ\\H30[3,4]",
	"CalculateJ\\H30[4,1]",
	"CalculateJ\\H30[4,2]",
	"CalculateJ\\H30[4,3]",
	"CalculateJ\\H30[4,4]",
	"CalculateJ\\H40[1,1]",
	"CalculateJ\\H40[1,2]",
	"CalculateJ\\H40[1,3]",
	"CalculateJ\\H40[1,4]",
	"CalculateJ\\H40[2,1]",
	"CalculateJ\\H40[2,2]",
	"CalculateJ\\H40[2,3]",
	"CalculateJ\\H40[2,4]",
	"CalculateJ\\H40[3,1]",
	"CalculateJ\\H40[3,2]",
	"CalculateJ\\H40[3,3]",
	"CalculateJ\\H40[3,4]",
	"CalculateJ\\H40[4,1]",
	"CalculateJ\\H40[4,2]",
	"CalculateJ\\H40[4,3]",
	"CalculateJ\\H40[4,4]",
	"CalculateJ\\H50[1,1]",
	"CalculateJ\\H50[1,2]",
	"CalculateJ\\H50[1,3]",
	"CalculateJ\\H50[1,4]",
	"CalculateJ\\H50[2,1]",
	"CalculateJ\\H50[2,2]",
	"CalculateJ\\H50[2,3]",
	"CalculateJ\\H50[2,4]",
	"CalculateJ\\H50[3,1]",
	"CalculateJ\\H50[3,2]",
	"CalculateJ\\H50[3,3]",
	"CalculateJ\\H50[3,4]",
	"CalculateJ\\H50[4,1]",
	"CalculateJ\\H50[4,2]",
	"CalculateJ\\H50[4,3]",
	"CalculateJ\\H50[4,4]",
	"ControllableJ1\\joints.e[1]",
	"ControllableJ1\\joints.e[2]",
	"ControllableJ1\\joints.e[3]",
	"ControllableJ1\\joints.e[4]",
	"ControllableJ1\\joints.e[5]",
	"ControllableJ1\\tip.f[1]",
	"ControllableJ1\\tip.f[2]",
	"ControllableJ1\\tip.f[3]",
	"ControllableJ1\\tip.f[4]",
	"ControllableJ1\\tip.f[5]",
	"ControllableJ1\\tip.f[6]",
	"CtipControl1\\p.e[1]",
	"CtipControl1\\p.e[2]",
	"CtipControl1\\p.e[3]",
	"CtipControl1\\p.e[4]",
	"CtipControl1\\p.e[5]",
	"CtipControl1\\p.e[6]",
	"CtipControl1\\state[1,1]",
	"CtipControl1\\state[1,2]",
	"CtipControl1\\state[1,3]",
	"CtipControl1\\state[1,4]",
	"CtipControl1\\state[2,1]",
	"CtipControl1\\state[2,2]",
	"CtipControl1\\state[2,3]",
	"CtipControl1\\state[2,4]",
	"CtipControl1\\state[3,1]",
	"CtipControl1\\state[3,2]",
	"CtipControl1\\state[3,3]",
	"CtipControl1\\state[3,4]",
	"CtipControl1\\state[4,1]",
	"CtipControl1\\state[4,2]",
	"CtipControl1\\state[4,3]",
	"CtipControl1\\state[4,4]",
	"CtipControl1\\theta",
	"CtipControl1\\omega[1]",
	"CtipControl1\\omega[2]",
	"CtipControl1\\omega[3]",
	"CtipControl1\\Wr[1]",
	"CtipControl1\\Wr[2]",
	"CtipControl1\\Wr[3]",
	"CtipControl1\\Wr[4]",
	"CtipControl1\\Wr[5]",
	"CtipControl1\\Wr[6]",
	"CtipControl1\\Wt[1]",
	"CtipControl1\\Wt[2]",
	"CtipControl1\\Wt[3]",
	"CtipControl1\\Wt[4]",
	"CtipControl1\\Wt[5]",
	"CtipControl1\\Wt[6]",
	"CtipControl1\\temp",
	"OneJunction\\p1.e[1]",
	"OneJunction\\p1.e[2]",
	"OneJunction\\p1.e[3]",
	"OneJunction\\p1.e[4]",
	"OneJunction\\p1.e[5]",
	"OneJunction\\p1.e[6]",
	"OneJunction2\\p2.f[1]",
	"OneJunction2\\p2.f[2]",
	"OneJunction2\\p2.f[3]",
	"OneJunction2\\p2.f[4]",
	"OneJunction2\\p2.f[5]",
	"R\\p.e[1]",
	"R\\p.e[2]",
	"R\\p.e[3]",
	"R\\p.e[4]",
	"R\\p.e[5]",
	"R\\p.e[6]",
	"Splitter2\\input[1]",
	"Splitter2\\input[2]",
	"Splitter2\\input[3]",
	"Splitter2\\input[4]",
	"Splitter2\\input[5]",
	"VirtualPosition\\output[1,1]",
	"VirtualPosition\\output[1,2]",
	"VirtualPosition\\output[1,3]",
	"VirtualPosition\\output[1,4]",
	"VirtualPosition\\output[2,1]",
	"VirtualPosition\\output[2,2]",
	"VirtualPosition\\output[2,3]",
	"VirtualPosition\\output[2,4]",
	"VirtualPosition\\output[3,1]",
	"VirtualPosition\\output[3,2]",
	"VirtualPosition\\output[3,3]",
	"VirtualPosition\\output[3,4]",
	"VirtualPosition\\output[4,1]",
	"VirtualPosition\\output[4,2]",
	"VirtualPosition\\output[4,3]",
	"VirtualPosition\\output[4,4]",
	"VirtualPosition\\xyzQuart[1]",
	"VirtualPosition\\xyzQuart[2]",
	"VirtualPosition\\xyzQuart[3]",
	"VirtualPosition\\xyzQuart[4]",
	"VirtualPosition\\xyzQuart[5]",
	"VirtualPosition\\xyzQuart[6]",
	"VirtualPosition\\xyzQuart[7]",
	"VirtualPosition\\R[1,1]",
	"VirtualPosition\\R[1,2]",
	"VirtualPosition\\R[1,3]",
	"VirtualPosition\\R[2,1]",
	"VirtualPosition\\R[2,2]",
	"VirtualPosition\\R[2,3]",
	"VirtualPosition\\R[3,1]",
	"VirtualPosition\\R[3,2]",
	"VirtualPosition\\R[3,3]",
	"joints.e[1]",
	"joints.e[2]",
	"joints.e[3]",
	"joints.e[4]",
	"joints.e[5]",
	"joints.f[1]",
	"joints.f[2]",
	"joints.f[3]",
	"joints.f[4]",
	"joints.f[5]",
	"xyzQuart[1]",
	"xyzQuart[2]",
	"xyzQuart[3]",
	"xyzQuart[4]",
	"xyzQuart[5]",
	"xyzQuart[6]",
	"xyzQuart[7]",
	"Linkdim[1,1]",
	"Linkdim[1,2]",
	"Linkdim[1,3]",
	"Linkdim[1,4]",
	"Linkdim[1,5]",
	"Linkdim[1,6]",
	"Linkdim[2,1]",
	"Linkdim[2,2]",
	"Linkdim[2,3]",
	"Linkdim[2,4]",
	"Linkdim[2,5]",
	"Linkdim[2,6]",
	"Linkdim[3,1]",
	"Linkdim[3,2]",
	"Linkdim[3,3]",
	"Linkdim[3,4]",
	"Linkdim[3,5]",
	"Linkdim[3,6]",
	"q[1]",
	"q[2]",
	"q[3]",
	"q[4]",
	"q[5]",
	"output[1,1]",
	"output[1,2]",
	"output[1,3]",
	"output[1,4]",
	"output[2,1]",
	"output[2,2]",
	"output[2,3]",
	"output[2,4]",
	"output[3,1]",
	"output[3,2]",
	"output[3,3]",
	"output[3,4]",
	"output[4,1]",
	"output[4,2]",
	"output[4,3]",
	"output[4,4]"

	};
	std::string m_state_names[0+1] = {
			NULL
	};
	std::string m_rate_names[0+1] = {
			NULL
	};
	std::string m_matrix_names[112+1] = {
			"CalculateJ\\controllableJ",
	"CalculateJ\\Htip0",
	"CalculateJ\\Linkdim",
	"CalculateJ\\omega1",
	"CalculateJ\\omega2",
	"CalculateJ\\omega3",
	"CalculateJ\\omega4",
	"CalculateJ\\omega5",
	"CalculateJ\\uTr1refref",
	"CalculateJ\\uTr211",
	"CalculateJ\\uTr322",
	"CalculateJ\\uTr433",
	"CalculateJ\\uTr544",
	"CalculateJ\\R1ref",
	"CalculateJ\\R21",
	"CalculateJ\\R32",
	"CalculateJ\\R43",
	"CalculateJ\\R54",
	"CalculateJ\\Rtip5",
	"CalculateJ\\p1ref",
	"CalculateJ\\p21",
	"CalculateJ\\p32",
	"CalculateJ\\p43",
	"CalculateJ\\p54",
	"CalculateJ\\ptip5",
	"CalculateJ\\Href0",
	"CalculateJ\\H1ref",
	"CalculateJ\\H21",
	"CalculateJ\\H32",
	"CalculateJ\\H43",
	"CalculateJ\\H54",
	"CalculateJ\\Htip5",
	"CalculateJ\\H10",
	"CalculateJ\\H20",
	"CalculateJ\\H30",
	"CalculateJ\\H40",
	"CalculateJ\\H50",
	"ControllableJ1\\joints.e",
	"ControllableJ1\\tip.f",
	"CtipControl1\\p.e",
	"CtipControl1\\state",
	"CtipControl1\\omega",
	"CtipControl1\\Wr",
	"CtipControl1\\Wt",
	"OneJunction\\p1.e",
	"OneJunction2\\p2.f",
	"R\\p.e",
	"Splitter2\\input",
	"VirtualPosition\\output",
	"VirtualPosition\\xyzQuart",
	"VirtualPosition\\R",
	"joints.e",
	"joints.f",
	"xyzQuart",
	"Linkdim",
	"q",
	"output",
	"m_U1",
	"m_U2",
	"m_U3",
	"m_U4",
	"m_U5",
	"m_U6",
	"m_U7",
	"m_U8",
	"m_U9",
	"m_U10",
	"m_U11",
	"m_U12",
	"m_U13",
	"m_U14",
	"m_U15",
	"m_U16",
	"m_U17",
	"m_U18",
	"m_U19",
	"m_U20",
	"m_U21",
	"m_U22",
	"m_U23",
	"m_U24",
	"m_U25",
	"m_U26",
	"m_U27",
	"m_U28",
	"m_U29",
	"m_U30",
	"m_U31",
	"m_U32",
	"m_U33",
	"m_U34",
	"m_U35",
	"m_U36",
	"m_U37",
	"m_U38",
	"m_U39",
	"m_U40",
	"m_U41",
	"m_U42",
	"m_U43",
	"m_U44",
	"m_U45",
	"m_U46",
	"m_U47",
	"m_U48",
	"m_U49",
	"m_U50",
	"m_U51",
	"m_U52",
	"m_U53",
	"m_U54",
	"m_U55"

	};
	std::string m_favorite_par_names[0+1] = {
			NULL
	};
	std::string m_favorite_var_names[0+1] = {
			NULL
	};
}
interaction_control::interaction_control(void)
{
	m_start_time = 0.0;
	m_finish_time = 14.0;
	m_step_size = 0.001;
	m_time = 0;
	m_major = true;

	m_number_constants = 15;
	m_number_parameters = 2;
	m_number_initialvalues = 0;
	m_number_variables = 518;
	m_number_states = 0;
	m_number_rates = 0;
	m_number_matrices = 112;
	m_number_unnamed = 574;

	/* the variable arrays */
	m_C = new XXDouble[15 + 1];		/* constants */
	m_P = new XXDouble[2 + 1];		/* parameters */
	m_I = new XXDouble[0 + 1];		/* initial values */
	m_V = new XXDouble[518 + 1];		/* variables */
	m_s = new XXDouble[0 + 1];		/* states */
	m_R = new XXDouble[0 + 1];		/* rates (or new states) */
	m_M = new XXMatrix[112 + 1];		/* matrices */
	m_U = new XXDouble[574 + 1];		/* unnamed */
	m_workarray = new XXDouble[156 + 1];

	myintegmethod.Initialize(this);

	state = initialrun;
}

interaction_control::~interaction_control(void)
{
	/* free memory */
	delete[] m_C;
	delete[] m_P;
	delete[] m_I;
	delete[] m_V;
	delete[] m_s;
	delete[] m_R;
	delete[] m_M;
	delete[] m_U;
	delete[] m_workarray;
}

/* the initialization function for submodel */
void interaction_control::Initialize (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* initialization phase (allocating memory) */
	m_initialize = true;

	/* copy the inputs */
	m_time = t;

	/* set the constants */
	m_C[0] = 0.0;		/* CalculateJ\omega1 */
	m_C[1] = 0.0;
	m_C[2] = 1.0;
	m_C[3] = 0.0;		/* CalculateJ\omega2 */
	m_C[4] = 1.0;
	m_C[5] = 0.0;
	m_C[6] = 0.0;		/* CalculateJ\omega3 */
	m_C[7] = 1.0;
	m_C[8] = 0.0;
	m_C[9] = 0.0;		/* CalculateJ\omega4 */
	m_C[10] = 1.0;
	m_C[11] = 0.0;
	m_C[12] = 0.0;		/* CalculateJ\omega5 */
	m_C[13] = 0.0;
	m_C[14] = 1.0;


	/* set the parameters */
	m_P[0] = 0.001;		/* CtipControl1\CtipControl */
	m_P[1] = 30.0;		/* R\controlDamping */


	/* set the states */


	/* set the matrices */
	m_M[0].mat = &m_V[0];		/* CalculateJ\controllableJ */
	m_M[0].rows = 6;
	m_M[0].columns = 5;
	m_M[1].mat = &m_V[30];		/* CalculateJ\Htip0 */
	m_M[1].rows = 4;
	m_M[1].columns = 4;
	m_M[2].mat = &m_V[46];		/* CalculateJ\Linkdim */
	m_M[2].rows = 3;
	m_M[2].columns = 6;
	m_M[3].mat = &m_C[0];		/* CalculateJ\omega1 */
	m_M[3].rows = 3;
	m_M[3].columns = 1;
	m_M[4].mat = &m_C[3];		/* CalculateJ\omega2 */
	m_M[4].rows = 3;
	m_M[4].columns = 1;
	m_M[5].mat = &m_C[6];		/* CalculateJ\omega3 */
	m_M[5].rows = 3;
	m_M[5].columns = 1;
	m_M[6].mat = &m_C[9];		/* CalculateJ\omega4 */
	m_M[6].rows = 3;
	m_M[6].columns = 1;
	m_M[7].mat = &m_C[12];		/* CalculateJ\omega5 */
	m_M[7].rows = 3;
	m_M[7].columns = 1;
	m_M[8].mat = &m_V[64];		/* CalculateJ\uTr1refref */
	m_M[8].rows = 6;
	m_M[8].columns = 1;
	m_M[9].mat = &m_V[70];		/* CalculateJ\uTr211 */
	m_M[9].rows = 6;
	m_M[9].columns = 1;
	m_M[10].mat = &m_V[76];		/* CalculateJ\uTr322 */
	m_M[10].rows = 6;
	m_M[10].columns = 1;
	m_M[11].mat = &m_V[82];		/* CalculateJ\uTr433 */
	m_M[11].rows = 6;
	m_M[11].columns = 1;
	m_M[12].mat = &m_V[88];		/* CalculateJ\uTr544 */
	m_M[12].rows = 6;
	m_M[12].columns = 1;
	m_M[13].mat = &m_V[94];		/* CalculateJ\R1ref */
	m_M[13].rows = 3;
	m_M[13].columns = 3;
	m_M[14].mat = &m_V[103];		/* CalculateJ\R21 */
	m_M[14].rows = 3;
	m_M[14].columns = 3;
	m_M[15].mat = &m_V[112];		/* CalculateJ\R32 */
	m_M[15].rows = 3;
	m_M[15].columns = 3;
	m_M[16].mat = &m_V[121];		/* CalculateJ\R43 */
	m_M[16].rows = 3;
	m_M[16].columns = 3;
	m_M[17].mat = &m_V[130];		/* CalculateJ\R54 */
	m_M[17].rows = 3;
	m_M[17].columns = 3;
	m_M[18].mat = &m_V[139];		/* CalculateJ\Rtip5 */
	m_M[18].rows = 3;
	m_M[18].columns = 3;
	m_M[19].mat = &m_V[148];		/* CalculateJ\p1ref */
	m_M[19].rows = 3;
	m_M[19].columns = 1;
	m_M[20].mat = &m_V[151];		/* CalculateJ\p21 */
	m_M[20].rows = 3;
	m_M[20].columns = 1;
	m_M[21].mat = &m_V[154];		/* CalculateJ\p32 */
	m_M[21].rows = 3;
	m_M[21].columns = 1;
	m_M[22].mat = &m_V[157];		/* CalculateJ\p43 */
	m_M[22].rows = 3;
	m_M[22].columns = 1;
	m_M[23].mat = &m_V[160];		/* CalculateJ\p54 */
	m_M[23].rows = 3;
	m_M[23].columns = 1;
	m_M[24].mat = &m_V[163];		/* CalculateJ\ptip5 */
	m_M[24].rows = 3;
	m_M[24].columns = 1;
	m_M[25].mat = &m_V[166];		/* CalculateJ\Href0 */
	m_M[25].rows = 4;
	m_M[25].columns = 4;
	m_M[26].mat = &m_V[182];		/* CalculateJ\H1ref */
	m_M[26].rows = 4;
	m_M[26].columns = 4;
	m_M[27].mat = &m_V[198];		/* CalculateJ\H21 */
	m_M[27].rows = 4;
	m_M[27].columns = 4;
	m_M[28].mat = &m_V[214];		/* CalculateJ\H32 */
	m_M[28].rows = 4;
	m_M[28].columns = 4;
	m_M[29].mat = &m_V[230];		/* CalculateJ\H43 */
	m_M[29].rows = 4;
	m_M[29].columns = 4;
	m_M[30].mat = &m_V[246];		/* CalculateJ\H54 */
	m_M[30].rows = 4;
	m_M[30].columns = 4;
	m_M[31].mat = &m_V[262];		/* CalculateJ\Htip5 */
	m_M[31].rows = 4;
	m_M[31].columns = 4;
	m_M[32].mat = &m_V[278];		/* CalculateJ\H10 */
	m_M[32].rows = 4;
	m_M[32].columns = 4;
	m_M[33].mat = &m_V[294];		/* CalculateJ\H20 */
	m_M[33].rows = 4;
	m_M[33].columns = 4;
	m_M[34].mat = &m_V[310];		/* CalculateJ\H30 */
	m_M[34].rows = 4;
	m_M[34].columns = 4;
	m_M[35].mat = &m_V[326];		/* CalculateJ\H40 */
	m_M[35].rows = 4;
	m_M[35].columns = 4;
	m_M[36].mat = &m_V[342];		/* CalculateJ\H50 */
	m_M[36].rows = 4;
	m_M[36].columns = 4;
	m_M[37].mat = &m_V[358];		/* ControllableJ1\joints.e */
	m_M[37].rows = 5;
	m_M[37].columns = 1;
	m_M[38].mat = &m_V[363];		/* ControllableJ1\tip.f */
	m_M[38].rows = 6;
	m_M[38].columns = 1;
	m_M[39].mat = &m_V[369];		/* CtipControl1\p.e */
	m_M[39].rows = 6;
	m_M[39].columns = 1;
	m_M[40].mat = &m_V[375];		/* CtipControl1\state */
	m_M[40].rows = 4;
	m_M[40].columns = 4;
	m_M[41].mat = &m_V[392];		/* CtipControl1\omega */
	m_M[41].rows = 3;
	m_M[41].columns = 1;
	m_M[42].mat = &m_V[395];		/* CtipControl1\Wr */
	m_M[42].rows = 6;
	m_M[42].columns = 1;
	m_M[43].mat = &m_V[401];		/* CtipControl1\Wt */
	m_M[43].rows = 6;
	m_M[43].columns = 1;
	m_M[44].mat = &m_V[408];		/* OneJunction\p1.e */
	m_M[44].rows = 6;
	m_M[44].columns = 1;
	m_M[45].mat = &m_V[414];		/* OneJunction2\p2.f */
	m_M[45].rows = 5;
	m_M[45].columns = 1;
	m_M[46].mat = &m_V[419];		/* R\p.e */
	m_M[46].rows = 6;
	m_M[46].columns = 1;
	m_M[47].mat = &m_V[425];		/* Splitter2\input */
	m_M[47].rows = 5;
	m_M[47].columns = 1;
	m_M[48].mat = &m_V[430];		/* VirtualPosition\output */
	m_M[48].rows = 4;
	m_M[48].columns = 4;
	m_M[49].mat = &m_V[446];		/* VirtualPosition\xyzQuart */
	m_M[49].rows = 7;
	m_M[49].columns = 1;
	m_M[50].mat = &m_V[453];		/* VirtualPosition\R */
	m_M[50].rows = 3;
	m_M[50].columns = 3;
	m_M[51].mat = &m_V[462];		/* joints.e */
	m_M[51].rows = 5;
	m_M[51].columns = 1;
	m_M[52].mat = &m_V[467];		/* joints.f */
	m_M[52].rows = 5;
	m_M[52].columns = 1;
	m_M[53].mat = &m_V[472];		/* xyzQuart */
	m_M[53].rows = 7;
	m_M[53].columns = 1;
	m_M[54].mat = &m_V[479];		/* Linkdim */
	m_M[54].rows = 3;
	m_M[54].columns = 6;
	m_M[55].mat = &m_V[497];		/* q */
	m_M[55].rows = 5;
	m_M[55].columns = 1;
	m_M[56].mat = &m_V[502];		/* output */
	m_M[56].rows = 4;
	m_M[56].columns = 4;
	m_M[57].mat = &m_U[0];		/* m_U1 */
	m_M[57].rows = 3;
	m_M[57].columns = 3;
	m_M[58].mat = &m_U[9];		/* m_U2 */
	m_M[58].rows = 3;
	m_M[58].columns = 1;
	m_M[59].mat = &m_U[12];		/* m_U3 */
	m_M[59].rows = 3;
	m_M[59].columns = 1;
	m_M[60].mat = &m_U[15];		/* m_U4 */
	m_M[60].rows = 3;
	m_M[60].columns = 3;
	m_M[61].mat = &m_U[24];		/* m_U5 */
	m_M[61].rows = 3;
	m_M[61].columns = 1;
	m_M[62].mat = &m_U[27];		/* m_U6 */
	m_M[62].rows = 3;
	m_M[62].columns = 1;
	m_M[63].mat = &m_U[30];		/* m_U7 */
	m_M[63].rows = 3;
	m_M[63].columns = 3;
	m_M[64].mat = &m_U[39];		/* m_U8 */
	m_M[64].rows = 3;
	m_M[64].columns = 1;
	m_M[65].mat = &m_U[42];		/* m_U9 */
	m_M[65].rows = 3;
	m_M[65].columns = 1;
	m_M[66].mat = &m_U[45];		/* m_U10 */
	m_M[66].rows = 3;
	m_M[66].columns = 3;
	m_M[67].mat = &m_U[54];		/* m_U11 */
	m_M[67].rows = 3;
	m_M[67].columns = 1;
	m_M[68].mat = &m_U[57];		/* m_U12 */
	m_M[68].rows = 3;
	m_M[68].columns = 1;
	m_M[69].mat = &m_U[60];		/* m_U13 */
	m_M[69].rows = 3;
	m_M[69].columns = 3;
	m_M[70].mat = &m_U[69];		/* m_U14 */
	m_M[70].rows = 3;
	m_M[70].columns = 1;
	m_M[71].mat = &m_U[72];		/* m_U15 */
	m_M[71].rows = 3;
	m_M[71].columns = 1;
	m_M[72].mat = &m_U[75];		/* m_U16 */
	m_M[72].rows = 3;
	m_M[72].columns = 3;
	m_M[73].mat = &m_U[84];		/* m_U17 */
	m_M[73].rows = 3;
	m_M[73].columns = 1;
	m_M[74].mat = &m_U[87];		/* m_U18 */
	m_M[74].rows = 6;
	m_M[74].columns = 1;
	m_M[75].mat = &m_U[93];		/* m_U19 */
	m_M[75].rows = 6;
	m_M[75].columns = 6;
	m_M[76].mat = &m_U[129];		/* m_U20 */
	m_M[76].rows = 3;
	m_M[76].columns = 3;
	m_M[77].mat = &m_U[138];		/* m_U21 */
	m_M[77].rows = 3;
	m_M[77].columns = 3;
	m_M[78].mat = &m_U[147];		/* m_U22 */
	m_M[78].rows = 3;
	m_M[78].columns = 3;
	m_M[79].mat = &m_U[156];		/* m_U23 */
	m_M[79].rows = 3;
	m_M[79].columns = 3;
	m_M[80].mat = &m_U[165];		/* m_U24 */
	m_M[80].rows = 3;
	m_M[80].columns = 1;
	m_M[81].mat = &m_U[168];		/* m_U25 */
	m_M[81].rows = 3;
	m_M[81].columns = 3;
	m_M[82].mat = &m_U[177];		/* m_U26 */
	m_M[82].rows = 3;
	m_M[82].columns = 3;
	m_M[83].mat = &m_U[186];		/* m_U27 */
	m_M[83].rows = 3;
	m_M[83].columns = 3;
	m_M[84].mat = &m_U[195];		/* m_U28 */
	m_M[84].rows = 3;
	m_M[84].columns = 1;
	m_M[85].mat = &m_U[198];		/* m_U29 */
	m_M[85].rows = 3;
	m_M[85].columns = 3;
	m_M[86].mat = &m_U[207];		/* m_U30 */
	m_M[86].rows = 3;
	m_M[86].columns = 1;
	m_M[87].mat = &m_U[210];		/* m_U31 */
	m_M[87].rows = 3;
	m_M[87].columns = 1;
	m_M[88].mat = &m_U[213];		/* m_U32 */
	m_M[88].rows = 6;
	m_M[88].columns = 1;
	m_M[89].mat = &m_U[219];		/* m_U33 */
	m_M[89].rows = 6;
	m_M[89].columns = 6;
	m_M[90].mat = &m_U[255];		/* m_U34 */
	m_M[90].rows = 6;
	m_M[90].columns = 1;
	m_M[91].mat = &m_U[261];		/* m_U35 */
	m_M[91].rows = 6;
	m_M[91].columns = 6;
	m_M[92].mat = &m_U[297];		/* m_U36 */
	m_M[92].rows = 6;
	m_M[92].columns = 1;
	m_M[93].mat = &m_U[303];		/* m_U37 */
	m_M[93].rows = 6;
	m_M[93].columns = 6;
	m_M[94].mat = &m_U[339];		/* m_U38 */
	m_M[94].rows = 6;
	m_M[94].columns = 1;
	m_M[95].mat = &m_U[345];		/* m_U39 */
	m_M[95].rows = 6;
	m_M[95].columns = 6;
	m_M[96].mat = &m_U[381];		/* m_U40 */
	m_M[96].rows = 4;
	m_M[96].columns = 4;
	m_M[97].mat = &m_U[397];		/* m_U41 */
	m_M[97].rows = 1;
	m_M[97].columns = 1;
	m_M[98].mat = &m_U[398];		/* m_U42 */
	m_M[98].rows = 3;
	m_M[98].columns = 3;
	m_M[99].mat = &m_U[407];		/* m_U43 */
	m_M[99].rows = 1;
	m_M[99].columns = 1;
	m_M[100].mat = &m_U[408];		/* m_U44 */
	m_M[100].rows = 1;
	m_M[100].columns = 1;
	m_M[101].mat = &m_U[409];		/* m_U45 */
	m_M[101].rows = 3;
	m_M[101].columns = 1;
	m_M[102].mat = &m_U[412];		/* m_U46 */
	m_M[102].rows = 3;
	m_M[102].columns = 1;
	m_M[103].mat = &m_U[415];		/* m_U47 */
	m_M[103].rows = 3;
	m_M[103].columns = 1;
	m_M[104].mat = &m_U[418];		/* m_U48 */
	m_M[104].rows = 3;
	m_M[104].columns = 1;
	m_M[105].mat = &m_U[421];		/* m_U49 */
	m_M[105].rows = 3;
	m_M[105].columns = 1;
	m_M[106].mat = &m_U[424];		/* m_U50 */
	m_M[106].rows = 6;
	m_M[106].columns = 6;
	m_M[107].mat = &m_U[460];		/* m_U51 */
	m_M[107].rows = 6;
	m_M[107].columns = 6;
	m_M[108].mat = &m_U[496];		/* m_U52 */
	m_M[108].rows = 6;
	m_M[108].columns = 6;
	m_M[109].mat = &m_U[532];		/* m_U53 */
	m_M[109].rows = 6;
	m_M[109].columns = 1;
	m_M[110].mat = &m_U[538];		/* m_U54 */
	m_M[110].rows = 6;
	m_M[110].columns = 1;
	m_M[111].mat = &m_U[544];		/* m_U55 */
	m_M[111].rows = 5;
	m_M[111].columns = 6;


	/* calculate initial and static equations */
	CalculateInitial ();
	CalculateStatic ();

	/* end of initialization phase */
	m_initialize = false;

	state = initialrun;
}

/* the function that calculates the submodel */
void interaction_control::Calculate (XXDouble *u, XXDouble *y /*, XXDouble t*/)
{
	/* another precessor submodel could determine the parameters of this submodel
	   and therefore the static parameter calculations need to be performed. */
	CalculateStatic ();

	switch (state)
	{
		case initialrun:	/* calculate the model for the first time */
			CopyInputsToVariables (u);
			CalculateInput ();
			CalculateDynamic();
			CalculateOutput ();
			CopyVariablesToOutputs (y);
			state = mainrun;
			break;
		case mainrun:	/* calculate the model */


				CopyInputsToVariables (u);
				CalculateInput ();
				myintegmethod.Step();
				CalculateOutput ();
				CopyVariablesToOutputs (y);
			break;
		case finished:
			throw std::logic_error("The simulation was finished");
			break;
		default:
			throw std::logic_error("The simulation state machine is inconsistent");
			break;
	}
}

/* the termination function for submodel */
void interaction_control::Terminate (XXDouble *u, XXDouble *y /*, XXDouble t */)
{
	/* copy the inputs */
	CopyInputsToVariables (u);

	/* calculate the final model equations */
	CalculateFinal ();

	/* set the outputs */
	CopyVariablesToOutputs (y);
}


/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void interaction_control::CalculateInitial (void)
{

}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void interaction_control::CalculateStatic (void)
{
	/* CalculateJ\Href0 = homogeneous (eye (3), [0; 0; 0]); */
	XXMatrixEye (&m_M[57]);
	m_M[58].mat[0] = 0.0;
	m_M[58].mat[1] = 0.0;
	m_M[58].mat[2] = 0.0;
	XXMatrixHomogeneous (&m_M[25], &m_M[57], &m_M[58]);

	/* CalculateJ\Rtip5 = eye (3); */
	XXMatrixEye (&m_M[18]);

	/* CalculateJ\uTr1refref[1:3] = CalculateJ\omega1; */
	m_M[8].mat[0] = m_M[3].mat[0];
	m_M[8].mat[1] = m_M[3].mat[1];
	m_M[8].mat[2] = m_M[3].mat[2];

	/* CalculateJ\uTr211[1:3] = CalculateJ\omega2; */
	m_M[9].mat[0] = m_M[4].mat[0];
	m_M[9].mat[1] = m_M[4].mat[1];
	m_M[9].mat[2] = m_M[4].mat[2];

	/* CalculateJ\uTr322[1:3] = CalculateJ\omega3; */
	m_M[10].mat[0] = m_M[5].mat[0];
	m_M[10].mat[1] = m_M[5].mat[1];
	m_M[10].mat[2] = m_M[5].mat[2];

	/* CalculateJ\uTr433[1:3] = CalculateJ\omega4; */
	m_M[11].mat[0] = m_M[6].mat[0];
	m_M[11].mat[1] = m_M[6].mat[1];
	m_M[11].mat[2] = m_M[6].mat[2];

	/* CalculateJ\uTr544[1:3] = CalculateJ\omega5; */
	m_M[12].mat[0] = m_M[7].mat[0];
	m_M[12].mat[1] = m_M[7].mat[1];
	m_M[12].mat[2] = m_M[7].mat[2];

	/* CtipControl1\Wt[1:3] = 0; */
	m_M[43].mat[0] = 0.0;
	m_M[43].mat[1] = 0.0;
	m_M[43].mat[2] = 0.0;

	/* CtipControl1\Wr[4:6] = 0; */
	m_M[42].mat[3] = 0.0;
	m_M[42].mat[4] = 0.0;
	m_M[42].mat[5] = 0.0;

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void interaction_control::CalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void interaction_control::CalculateDynamic (void)
{
	/* OneJunction2\p2.f = joints.f; */
	XXMatrixMov (&m_M[45], &m_M[52]);

	/* VirtualPosition\xyzQuart = xyzQuart; */
	XXMatrixMov (&m_M[49], &m_M[53]);

	/* CalculateJ\Linkdim = Linkdim; */
	XXMatrixMov (&m_M[2], &m_M[54]);

	/* Splitter2\input = q; */
	XXMatrixMov (&m_M[47], &m_M[55]);

	/* CalculateJ\p1ref = CalculateJ\Linkdim[1:3,1]; */
	m_M[19].mat[0] = m_M[2].mat[0];
	m_M[19].mat[1] = m_M[2].mat[6];
	m_M[19].mat[2] = m_M[2].mat[12];

	/* CalculateJ\p21 = CalculateJ\Linkdim[1:3,2]; */
	m_M[20].mat[0] = m_M[2].mat[1];
	m_M[20].mat[1] = m_M[2].mat[7];
	m_M[20].mat[2] = m_M[2].mat[13];

	/* CalculateJ\p32 = CalculateJ\Linkdim[1:3,3]; */
	m_M[21].mat[0] = m_M[2].mat[2];
	m_M[21].mat[1] = m_M[2].mat[8];
	m_M[21].mat[2] = m_M[2].mat[14];

	/* CalculateJ\p43 = CalculateJ\Linkdim[1:3,4]; */
	m_M[22].mat[0] = m_M[2].mat[3];
	m_M[22].mat[1] = m_M[2].mat[9];
	m_M[22].mat[2] = m_M[2].mat[15];

	/* CalculateJ\p54 = CalculateJ\Linkdim[1:3,5]; */
	m_M[23].mat[0] = m_M[2].mat[4];
	m_M[23].mat[1] = m_M[2].mat[10];
	m_M[23].mat[2] = m_M[2].mat[16];

	/* CalculateJ\ptip5 = CalculateJ\Linkdim[1:3,6]; */
	m_M[24].mat[0] = m_M[2].mat[5];
	m_M[24].mat[1] = m_M[2].mat[11];
	m_M[24].mat[2] = m_M[2].mat[17];

	/* CalculateJ\Htip5 = homogeneous (CalculateJ\Rtip5, CalculateJ\ptip5); */
	XXMatrixHomogeneous (&m_M[31], &m_M[18], &m_M[24]);

	/* CalculateJ\uTr1refref[4:6] = skew (CalculateJ\Linkdim[1:3,1]) * CalculateJ\omega1; */
	m_M[61].mat[0] = m_M[2].mat[0];
	m_M[61].mat[1] = m_M[2].mat[6];
	m_M[61].mat[2] = m_M[2].mat[12];
	XXMatrixSkew (&m_M[60], &m_M[61]);
	XXMatrixMul (&m_M[59], &m_M[60], &m_M[3]);
	m_M[8].mat[3] = m_M[59].mat[0];
	m_M[8].mat[4] = m_M[59].mat[1];
	m_M[8].mat[5] = m_M[59].mat[2];

	/* CalculateJ\uTr211[4:6] = skew (CalculateJ\Linkdim[1:3,2]) * CalculateJ\omega2; */
	m_M[64].mat[0] = m_M[2].mat[1];
	m_M[64].mat[1] = m_M[2].mat[7];
	m_M[64].mat[2] = m_M[2].mat[13];
	XXMatrixSkew (&m_M[63], &m_M[64]);
	XXMatrixMul (&m_M[62], &m_M[63], &m_M[4]);
	m_M[9].mat[3] = m_M[62].mat[0];
	m_M[9].mat[4] = m_M[62].mat[1];
	m_M[9].mat[5] = m_M[62].mat[2];

	/* CalculateJ\uTr322[4:6] = skew (CalculateJ\Linkdim[1:3,3]) * CalculateJ\omega3; */
	m_M[67].mat[0] = m_M[2].mat[2];
	m_M[67].mat[1] = m_M[2].mat[8];
	m_M[67].mat[2] = m_M[2].mat[14];
	XXMatrixSkew (&m_M[66], &m_M[67]);
	XXMatrixMul (&m_M[65], &m_M[66], &m_M[5]);
	m_M[10].mat[3] = m_M[65].mat[0];
	m_M[10].mat[4] = m_M[65].mat[1];
	m_M[10].mat[5] = m_M[65].mat[2];

	/* CalculateJ\uTr433[4:6] = skew (CalculateJ\Linkdim[1:3,4]) * CalculateJ\omega4; */
	m_M[70].mat[0] = m_M[2].mat[3];
	m_M[70].mat[1] = m_M[2].mat[9];
	m_M[70].mat[2] = m_M[2].mat[15];
	XXMatrixSkew (&m_M[69], &m_M[70]);
	XXMatrixMul (&m_M[68], &m_M[69], &m_M[6]);
	m_M[11].mat[3] = m_M[68].mat[0];
	m_M[11].mat[4] = m_M[68].mat[1];
	m_M[11].mat[5] = m_M[68].mat[2];

	/* CalculateJ\uTr544[4:6] = skew (CalculateJ\Linkdim[1:3,5]) * CalculateJ\omega5; */
	m_M[73].mat[0] = m_M[2].mat[4];
	m_M[73].mat[1] = m_M[2].mat[10];
	m_M[73].mat[2] = m_M[2].mat[16];
	XXMatrixSkew (&m_M[72], &m_M[73]);
	XXMatrixMul (&m_M[71], &m_M[72], &m_M[7]);
	m_M[12].mat[3] = m_M[71].mat[0];
	m_M[12].mat[4] = m_M[71].mat[1];
	m_M[12].mat[5] = m_M[71].mat[2];

	/* CalculateJ\controllableJ[1:6,1] = Adjoint (CalculateJ\Href0) * CalculateJ\uTr1refref; */
	XXMatrixAdjoint (&m_M[75], &m_M[25]);
	XXMatrixMul (&m_M[74], &m_M[75], &m_M[8]);
	m_M[0].mat[0] = m_M[74].mat[0];
	m_M[0].mat[5] = m_M[74].mat[1];
	m_M[0].mat[10] = m_M[74].mat[2];
	m_M[0].mat[15] = m_M[74].mat[3];
	m_M[0].mat[20] = m_M[74].mat[4];
	m_M[0].mat[25] = m_M[74].mat[5];

	/* VirtualPosition\R = (eye (3) + skew (VirtualPosition\xyzQuart[4:6]) * sin (VirtualPosition\xyzQuart[7])) + (skew (VirtualPosition\xyzQuart[4:6]) * skew (VirtualPosition\xyzQuart[4:6])) * (1 - cos (VirtualPosition\xyzQuart[7])); */
	XXMatrixEye (&m_M[77]);
	m_M[80].mat[0] = m_M[49].mat[3];
	m_M[80].mat[1] = m_M[49].mat[4];
	m_M[80].mat[2] = m_M[49].mat[5];
	XXMatrixSkew (&m_M[79], &m_M[80]);
	XXMatrixScalarMul (&m_M[78], &m_M[79], sin (m_M[49].mat[6]));
	XXMatrixAdd (&m_M[76], &m_M[77], &m_M[78]);
	m_M[84].mat[0] = m_M[49].mat[3];
	m_M[84].mat[1] = m_M[49].mat[4];
	m_M[84].mat[2] = m_M[49].mat[5];
	XXMatrixSkew (&m_M[83], &m_M[84]);
	m_M[86].mat[0] = m_M[49].mat[3];
	m_M[86].mat[1] = m_M[49].mat[4];
	m_M[86].mat[2] = m_M[49].mat[5];
	XXMatrixSkew (&m_M[85], &m_M[86]);
	XXMatrixMul (&m_M[82], &m_M[83], &m_M[85]);
	XXMatrixScalarMul (&m_M[81], &m_M[82], (1.0 - cos (m_M[49].mat[6])));
	XXMatrixAdd (&m_M[50], &m_M[76], &m_M[81]);

	/* VirtualPosition\output = homogeneous (VirtualPosition\R, VirtualPosition\xyzQuart[1:3]); */
	m_M[87].mat[0] = m_M[49].mat[0];
	m_M[87].mat[1] = m_M[49].mat[1];
	m_M[87].mat[2] = m_M[49].mat[2];
	XXMatrixHomogeneous (&m_M[48], &m_M[50], &m_M[87]);

	/* CalculateJ\R1ref = [cos (Splitter2\input[1]), -sin (Splitter2\input[1]), 0; sin (Splitter2\input[1]), cos (Splitter2\input[1]), 0; 0, 0, 1]; */
	m_M[13].mat[0] = cos (m_M[47].mat[0]);
	m_M[13].mat[1] = -(sin (m_M[47].mat[0]));
	m_M[13].mat[2] = 0.0;
	m_M[13].mat[3] = sin (m_M[47].mat[0]);
	m_M[13].mat[4] = cos (m_M[47].mat[0]);
	m_M[13].mat[5] = 0.0;
	m_M[13].mat[6] = 0.0;
	m_M[13].mat[7] = 0.0;
	m_M[13].mat[8] = 1.0;

	/* CalculateJ\H1ref = homogeneous (CalculateJ\R1ref, CalculateJ\p1ref); */
	XXMatrixHomogeneous (&m_M[26], &m_M[13], &m_M[19]);

	/* CalculateJ\R21 = [cos (Splitter2\input[2]), 0, sin (Splitter2\input[2]); 0, 1, 0; -sin (Splitter2\input[2]), 0, cos (Splitter2\input[2])]; */
	m_M[14].mat[0] = cos (m_M[47].mat[1]);
	m_M[14].mat[1] = 0.0;
	m_M[14].mat[2] = sin (m_M[47].mat[1]);
	m_M[14].mat[3] = 0.0;
	m_M[14].mat[4] = 1.0;
	m_M[14].mat[5] = 0.0;
	m_M[14].mat[6] = -(sin (m_M[47].mat[1]));
	m_M[14].mat[7] = 0.0;
	m_M[14].mat[8] = cos (m_M[47].mat[1]);

	/* CalculateJ\H21 = homogeneous (CalculateJ\R21, CalculateJ\p21); */
	XXMatrixHomogeneous (&m_M[27], &m_M[14], &m_M[20]);

	/* CalculateJ\R32 = [cos (Splitter2\input[3]), 0, sin (Splitter2\input[3]); 0, 1, 0; -sin (Splitter2\input[3]), 0, cos (Splitter2\input[3])]; */
	m_M[15].mat[0] = cos (m_M[47].mat[2]);
	m_M[15].mat[1] = 0.0;
	m_M[15].mat[2] = sin (m_M[47].mat[2]);
	m_M[15].mat[3] = 0.0;
	m_M[15].mat[4] = 1.0;
	m_M[15].mat[5] = 0.0;
	m_M[15].mat[6] = -(sin (m_M[47].mat[2]));
	m_M[15].mat[7] = 0.0;
	m_M[15].mat[8] = cos (m_M[47].mat[2]);

	/* CalculateJ\H32 = homogeneous (CalculateJ\R32, CalculateJ\p32); */
	XXMatrixHomogeneous (&m_M[28], &m_M[15], &m_M[21]);

	/* CalculateJ\R43 = [cos (Splitter2\input[4]), 0, sin (Splitter2\input[4]); 0, 1, 0; -sin (Splitter2\input[4]), 0, cos (Splitter2\input[4])]; */
	m_M[16].mat[0] = cos (m_M[47].mat[3]);
	m_M[16].mat[1] = 0.0;
	m_M[16].mat[2] = sin (m_M[47].mat[3]);
	m_M[16].mat[3] = 0.0;
	m_M[16].mat[4] = 1.0;
	m_M[16].mat[5] = 0.0;
	m_M[16].mat[6] = -(sin (m_M[47].mat[3]));
	m_M[16].mat[7] = 0.0;
	m_M[16].mat[8] = cos (m_M[47].mat[3]);

	/* CalculateJ\H43 = homogeneous (CalculateJ\R43, CalculateJ\p43); */
	XXMatrixHomogeneous (&m_M[29], &m_M[16], &m_M[22]);

	/* CalculateJ\R54 = [cos (Splitter2\input[5]), -sin (Splitter2\input[5]), 0; sin (Splitter2\input[5]), cos (Splitter2\input[5]), 0; 0, 0, 1]; */
	m_M[17].mat[0] = cos (m_M[47].mat[4]);
	m_M[17].mat[1] = -(sin (m_M[47].mat[4]));
	m_M[17].mat[2] = 0.0;
	m_M[17].mat[3] = sin (m_M[47].mat[4]);
	m_M[17].mat[4] = cos (m_M[47].mat[4]);
	m_M[17].mat[5] = 0.0;
	m_M[17].mat[6] = 0.0;
	m_M[17].mat[7] = 0.0;
	m_M[17].mat[8] = 1.0;

	/* CalculateJ\H54 = homogeneous (CalculateJ\R54, CalculateJ\p54); */
	XXMatrixHomogeneous (&m_M[30], &m_M[17], &m_M[23]);

	/* CalculateJ\H10 = CalculateJ\Href0 * CalculateJ\H1ref; */
	XXMatrixMul (&m_M[32], &m_M[25], &m_M[26]);

	/* CalculateJ\H20 = CalculateJ\H10 * CalculateJ\H21; */
	XXMatrixMul (&m_M[33], &m_M[32], &m_M[27]);

	/* CalculateJ\H30 = CalculateJ\H20 * CalculateJ\H32; */
	XXMatrixMul (&m_M[34], &m_M[33], &m_M[28]);

	/* CalculateJ\H40 = CalculateJ\H30 * CalculateJ\H43; */
	XXMatrixMul (&m_M[35], &m_M[34], &m_M[29]);

	/* CalculateJ\H50 = CalculateJ\H40 * CalculateJ\H54; */
	XXMatrixMul (&m_M[36], &m_M[35], &m_M[30]);

	/* CalculateJ\Htip0 = CalculateJ\H50 * CalculateJ\Htip5; */
	XXMatrixMul (&m_M[1], &m_M[36], &m_M[31]);

	/* CalculateJ\controllableJ[1:6,2] = Adjoint (CalculateJ\H10) * CalculateJ\uTr211; */
	XXMatrixAdjoint (&m_M[89], &m_M[32]);
	XXMatrixMul (&m_M[88], &m_M[89], &m_M[9]);
	m_M[0].mat[1] = m_M[88].mat[0];
	m_M[0].mat[6] = m_M[88].mat[1];
	m_M[0].mat[11] = m_M[88].mat[2];
	m_M[0].mat[16] = m_M[88].mat[3];
	m_M[0].mat[21] = m_M[88].mat[4];
	m_M[0].mat[26] = m_M[88].mat[5];

	/* CalculateJ\controllableJ[1:6,3] = Adjoint (CalculateJ\H20) * CalculateJ\uTr322; */
	XXMatrixAdjoint (&m_M[91], &m_M[33]);
	XXMatrixMul (&m_M[90], &m_M[91], &m_M[10]);
	m_M[0].mat[2] = m_M[90].mat[0];
	m_M[0].mat[7] = m_M[90].mat[1];
	m_M[0].mat[12] = m_M[90].mat[2];
	m_M[0].mat[17] = m_M[90].mat[3];
	m_M[0].mat[22] = m_M[90].mat[4];
	m_M[0].mat[27] = m_M[90].mat[5];

	/* CalculateJ\controllableJ[1:6,4] = Adjoint (CalculateJ\H30) * CalculateJ\uTr433; */
	XXMatrixAdjoint (&m_M[93], &m_M[34]);
	XXMatrixMul (&m_M[92], &m_M[93], &m_M[11]);
	m_M[0].mat[3] = m_M[92].mat[0];
	m_M[0].mat[8] = m_M[92].mat[1];
	m_M[0].mat[13] = m_M[92].mat[2];
	m_M[0].mat[18] = m_M[92].mat[3];
	m_M[0].mat[23] = m_M[92].mat[4];
	m_M[0].mat[28] = m_M[92].mat[5];

	/* CalculateJ\controllableJ[1:6,5] = Adjoint (CalculateJ\H40) * CalculateJ\uTr544; */
	XXMatrixAdjoint (&m_M[95], &m_M[35]);
	XXMatrixMul (&m_M[94], &m_M[95], &m_M[12]);
	m_M[0].mat[4] = m_M[94].mat[0];
	m_M[0].mat[9] = m_M[94].mat[1];
	m_M[0].mat[14] = m_M[94].mat[2];
	m_M[0].mat[19] = m_M[94].mat[3];
	m_M[0].mat[24] = m_M[94].mat[4];
	m_M[0].mat[29] = m_M[94].mat[5];

	/* ControllableJ1\tip.f = CalculateJ\controllableJ * OneJunction2\p2.f; */
	XXMatrixMul (&m_M[38], &m_M[0], &m_M[45]);

	/* output = CalculateJ\Htip0; */
	XXMatrixMov (&m_M[56], &m_M[1]);

	/* CtipControl1\state = inverse (VirtualPosition\output) * CalculateJ\Htip0; */
	XXMatrixInverse (&m_M[96], &m_M[48], m_workarray);
	XXMatrixMul (&m_M[40], &m_M[96], &m_M[1]);

	/* CtipControl1\temp = (trace (CtipControl1\state[1:3,1:3]) - 1) / 2; */
	m_M[98].mat[0] = m_M[40].mat[0];
	m_M[98].mat[1] = m_M[40].mat[1];
	m_M[98].mat[2] = m_M[40].mat[2];
	m_M[98].mat[3] = m_M[40].mat[4];
	m_M[98].mat[4] = m_M[40].mat[5];
	m_M[98].mat[5] = m_M[40].mat[6];
	m_M[98].mat[6] = m_M[40].mat[8];
	m_M[98].mat[7] = m_M[40].mat[9];
	m_M[98].mat[8] = m_M[40].mat[10];
	m_M[97].mat[0] = XXMatrixTrace (&m_M[98]);
	m_V[407] = (XXMatrixTrace (&m_M[98]) - 1.0) / 2.0;

	/* if (CtipControl1\temp < -1) */
	if (m_V[407] < -1.0)
	{
		/* CtipControl1\temp = -1; */
		m_V[407] = -1.0;
	}

	/* if (CtipControl1\temp > 1) */
	if (m_V[407] > 1.0)
	{
		/* CtipControl1\temp = 1; */
		m_V[407] = 1.0;
	}

	/* CtipControl1\theta = arccos (CtipControl1\temp); */
	m_V[391] = acos (m_V[407]);

	/* if (CtipControl1\theta == 0) */
	if (m_V[391] == 0.0)
	{
		/* CtipControl1\omega = 0; */
		XXMatrixScalarMov (&m_M[41], 0.0);
	}
	else
	{
		/* CtipControl1\omega = (1 / (2 * sin (CtipControl1\theta))) * [CtipControl1\state[3,2] - CtipControl1\state[2,3]; CtipControl1\state[1,3] - CtipControl1\state[3,1]; CtipControl1\state[2,1] - CtipControl1\state[1,2]]; */
		m_M[101].mat[0] = m_M[40].mat[9] - m_M[40].mat[6];
		m_M[101].mat[1] = m_M[40].mat[2] - m_M[40].mat[8];
		m_M[101].mat[2] = m_M[40].mat[4] - m_M[40].mat[1];
		XXScalarMatrixMul (&m_M[41], (1.0 / (2.0 * sin (m_V[391]))), &m_M[101]);
	}

	/* CtipControl1\Wt[4:6] = CtipControl1\state[1:3,4] / CtipControl1\CtipControl; */
	m_M[103].mat[0] = m_M[40].mat[3];
	m_M[103].mat[1] = m_M[40].mat[7];
	m_M[103].mat[2] = m_M[40].mat[11];
	XXMatrixScalarDiv (&m_M[102], &m_M[103], m_P[0]);
	m_M[43].mat[3] = m_M[102].mat[0];
	m_M[43].mat[4] = m_M[102].mat[1];
	m_M[43].mat[5] = m_M[102].mat[2];

	/* CtipControl1\Wr[1:3] = (CtipControl1\theta * CtipControl1\omega) / (CtipControl1\CtipControl); */
	XXScalarMatrixMul (&m_M[105], m_V[391], &m_M[41]);
	XXMatrixScalarDiv (&m_M[104], &m_M[105], (m_P[0]));
	m_M[42].mat[0] = m_M[104].mat[0]/10.0;
	m_M[42].mat[1] = m_M[104].mat[1]/10.0;
	m_M[42].mat[2] = m_M[104].mat[2]/10.0;

	/* CtipControl1\p.e = inverse (transpose (Adjoint (VirtualPosition\output))) * (CtipControl1\Wt + CtipControl1\Wr); */
	XXMatrixAdjoint (&m_M[108], &m_M[48]);
	XXMatrixTranspose (&m_M[107], &m_M[108]);
	XXMatrixInverse (&m_M[106], &m_M[107], m_workarray);
	XXMatrixAdd (&m_M[109], &m_M[43], &m_M[42]);
	XXMatrixMul (&m_M[39], &m_M[106], &m_M[109]);

	/* R\p.e = R\controlDamping * ControllableJ1\tip.f; */
	XXScalarMatrixMul (&m_M[46], m_P[1], &m_M[38]);

	/* OneJunction\p1.e = -(CtipControl1\p.e + R\p.e); */
	XXMatrixAdd (&m_M[110], &m_M[39], &m_M[46]);
	XXMatrixInv (&m_M[44], &m_M[110]);

	/* ControllableJ1\joints.e = transpose (CalculateJ\controllableJ) * OneJunction\p1.e; */
	XXMatrixTranspose (&m_M[111], &m_M[0]);
	XXMatrixMul (&m_M[37], &m_M[111], &m_M[44]);

	/* joints.e = ControllableJ1\joints.e; */
	XXMatrixMov (&m_M[51], &m_M[37]);

}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void interaction_control::CalculateOutput (void)
{

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void interaction_control::CalculateFinal (void)
{

}


