/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: ControlYoubotArmInteraction_v2
 *  expmt: ControlYoubotArmInteraction_v2
 *  date:  April 12, 2011
 *  time:  4:52:06 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
