/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: ControlYoubotFullInteraction_v1
 *  expmt: ControlYoubotFullInteraction_v1
 *  date:  April 17, 2011
 *  time:  11:51:38 am
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
