/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: youBot_control_gazebo
 *  expmt: youBot_control_gazebo
 *  date:  April 20, 2011
 *  time:  12:30:15 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
