/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  model: ControlYoubotFullInteraction_v1
 *  expmt: ControlYoubotFullInteraction_v1
 *  date:  April 17, 2011
 *  time:  11:22:08 am
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

