/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  model: ControlYoubotArmInteraction_v1
 *  expmt: ControlYoubotArmInteraction_v1
 *  date:  April 9, 2011
 *  time:  2:33:40 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

