/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  model: ControlYoubotArmInteraction
 *  expmt: ControlYoubotArmInteraction
 *  date:  April 8, 2011
 *  time:  5:53:21 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

