#!/bin/bash
# author: Sebastian Blumenthal
# date: 16.01.2011
#
# This scripts starts the youBot OODL driver for ROS with root permission. 
# The driver needs root access for the EtherCat driver.
#
#
# Usage: Just run this script (without any parameters): ./start_youbot_oodl_driver
# NOTE: setup.sh is assumed to be in ~/ros/setup.sh
# ---- 

echo "Please run 'roslaunch youbot_oodl youbot_oodl_driver.launch' instead."

