/**********************************************************
 * This file is generated by 20-sim C++ Code Generator
 *
 *  file:  PositionInteractionControl.cpp
 *  subm:  PositionInteractionControl
 *  model: ControlYoubotArmInteraction_v1
 *  expmt: ControlYoubotArmInteraction_v1
 *  date:  April 9, 2011
 *  time:  2:33:40 pm
 *  user:  Campuslicentie
 *  from:  Universiteit Twente
 *  build: 4.1.2.2
 **********************************************************/

/* Standard include files */
#include <stdio.h>
#include <math.h>
#include <stdexcept>

/* 20-sim include files */
#include "PositionInteractionControl.h"

	/* this PRIVATE function sets the input variables from the input vector */
void PositionInteractionControl::CopyInputsToVariables (XXDouble *u)
{
	/* copy the input vector to the input variables */
	m_V[478] = u[0];		/* joints.f */
	m_V[479] = u[1];
	m_V[480] = u[2];
	m_V[481] = u[3];
	m_V[482] = u[4];
	m_V[489] = u[5];		/* Linkdim */
	m_V[490] = u[6];
	m_V[491] = u[7];
	m_V[492] = u[8];
	m_V[493] = u[9];
	m_V[494] = u[10];
	m_V[495] = u[11];
	m_V[496] = u[12];
	m_V[497] = u[13];
	m_V[498] = u[14];
	m_V[499] = u[15];
	m_V[500] = u[16];
	m_V[501] = u[17];
	m_V[502] = u[18];
	m_V[503] = u[19];
	m_V[504] = u[20];
	m_V[505] = u[21];
	m_V[506] = u[22];
	m_V[507] = u[23];		/* q */
	m_V[508] = u[24];
	m_V[509] = u[25];
	m_V[510] = u[26];
	m_V[511] = u[27];
	m_V[483] = u[28];		/* xyzrpy */
	m_V[484] = u[29];
	m_V[485] = u[30];
	m_V[486] = u[31];
	m_V[487] = u[32];
	m_V[488] = u[33];

}

/* this PRIVATE function uses the output variables to fill the output vector */
void PositionInteractionControl::CopyVariablesToOutputs (XXDouble *y)
{
	/* copy the output variables to the output vector */
	y[0] = 	m_V[473];		/* joints.e */
	y[1] = 	m_V[474];
	y[2] = 	m_V[475];
	y[3] = 	m_V[476];
	y[4] = 	m_V[477];
	y[5] = 	m_V[512];		/* output */
	y[6] = 	m_V[513];
	y[7] = 	m_V[514];
	y[8] = 	m_V[515];
	y[9] = 	m_V[516];
	y[10] = 	m_V[517];
	y[11] = 	m_V[518];
	y[12] = 	m_V[519];
	y[13] = 	m_V[520];
	y[14] = 	m_V[521];
	y[15] = 	m_V[522];
	y[16] = 	m_V[523];
	y[17] = 	m_V[524];
	y[18] = 	m_V[525];
	y[19] = 	m_V[526];
	y[20] = 	m_V[527];

}

PositionInteractionControl::PositionInteractionControl(void)
{
	m_start_time = 0.0;
	m_finish_time = 10.0;
	m_step_size = 0.001;
	m_time = 0;
	m_major = true;

	m_number_constants = 15;
	m_number_parameters = 1;
	m_number_initialvalues = 0;
	m_number_variables = 528;
	m_number_states = 0;
	m_number_rates = 0;
	m_number_matrices = 103;
	m_number_unnamed = 505;

	/* the variable arrays */
	m_C = new XXDouble[15 + 1];		/* constants */
	m_P = new XXDouble[1 + 1];		/* parameters */
	m_I = new XXDouble[0 + 1];		/* initial values */
	m_V = new XXDouble[528 + 1];		/* variables */
	m_s = new XXDouble[0 + 1];		/* states */
	m_R = new XXDouble[0 + 1];		/* rates (or new states) */
	m_M = new XXMatrix[103 + 1];		/* matrices */
	m_U = new XXDouble[505 + 1];		/* unnamed */
	m_workarray = new XXDouble[156 + 1];

	myintegmethod.Initialize(this);

	state = initialrun;
}

PositionInteractionControl::~PositionInteractionControl(void)
{
	/* free memory */
	delete[] m_C;
	delete[] m_P;
	delete[] m_I;
	delete[] m_V;
	delete[] m_s;
	delete[] m_R;
	delete[] m_M;
	delete[] m_U;
	delete[] m_workarray;
}

/* the initialization function for submodel */
void PositionInteractionControl::Initialize (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* initialization phase (allocating memory) */
	m_initialize = true;

	/* copy the inputs */
	m_time = t;

	/* set the constants */
	m_C[0] = 0.0;		/* CalculateJ\omega1 */
	m_C[1] = 0.0;		
	m_C[2] = -1.0;		
	m_C[3] = 0.0;		/* CalculateJ\omega2 */
	m_C[4] = 1.0;		
	m_C[5] = 0.0;		
	m_C[6] = 0.0;		/* CalculateJ\omega3 */
	m_C[7] = 1.0;		
	m_C[8] = 0.0;		
	m_C[9] = 0.0;		/* CalculateJ\omega4 */
	m_C[10] = 1.0;		
	m_C[11] = 0.0;		
	m_C[12] = 0.0;		/* CalculateJ\omega5 */
	m_C[13] = 0.0;		
	m_C[14] = 1.0;		


	/* set the parameters */
	m_P[0] = 0.07;		/* CtipControl1\CtipControl */


	/* set the states */


	/* set the matrices */
	m_M[0].mat = &m_V[0];		/* CalculateJ\controllableJ */
	m_M[0].rows = 6;
	m_M[0].columns = 5;
	m_M[1].mat = &m_V[30];		/* CalculateJ\Htip0 */
	m_M[1].rows = 4;
	m_M[1].columns = 4;
	m_M[2].mat = &m_V[46];		/* CalculateJ\Linkdim */
	m_M[2].rows = 3;
	m_M[2].columns = 6;
	m_M[3].mat = &m_V[64];		/* CalculateJ\q */
	m_M[3].rows = 5;
	m_M[3].columns = 1;
	m_M[4].mat = &m_C[0];		/* CalculateJ\omega1 */
	m_M[4].rows = 3;
	m_M[4].columns = 1;
	m_M[5].mat = &m_C[3];		/* CalculateJ\omega2 */
	m_M[5].rows = 3;
	m_M[5].columns = 1;
	m_M[6].mat = &m_C[6];		/* CalculateJ\omega3 */
	m_M[6].rows = 3;
	m_M[6].columns = 1;
	m_M[7].mat = &m_C[9];		/* CalculateJ\omega4 */
	m_M[7].rows = 3;
	m_M[7].columns = 1;
	m_M[8].mat = &m_C[12];		/* CalculateJ\omega5 */
	m_M[8].rows = 3;
	m_M[8].columns = 1;
	m_M[9].mat = &m_V[69];		/* CalculateJ\uTr1refref */
	m_M[9].rows = 6;
	m_M[9].columns = 1;
	m_M[10].mat = &m_V[75];		/* CalculateJ\uTr211 */
	m_M[10].rows = 6;
	m_M[10].columns = 1;
	m_M[11].mat = &m_V[81];		/* CalculateJ\uTr322 */
	m_M[11].rows = 6;
	m_M[11].columns = 1;
	m_M[12].mat = &m_V[87];		/* CalculateJ\uTr433 */
	m_M[12].rows = 6;
	m_M[12].columns = 1;
	m_M[13].mat = &m_V[93];		/* CalculateJ\uTr544 */
	m_M[13].rows = 6;
	m_M[13].columns = 1;
	m_M[14].mat = &m_V[99];		/* CalculateJ\R1ref */
	m_M[14].rows = 3;
	m_M[14].columns = 3;
	m_M[15].mat = &m_V[108];		/* CalculateJ\R21 */
	m_M[15].rows = 3;
	m_M[15].columns = 3;
	m_M[16].mat = &m_V[117];		/* CalculateJ\R32 */
	m_M[16].rows = 3;
	m_M[16].columns = 3;
	m_M[17].mat = &m_V[126];		/* CalculateJ\R43 */
	m_M[17].rows = 3;
	m_M[17].columns = 3;
	m_M[18].mat = &m_V[135];		/* CalculateJ\R54 */
	m_M[18].rows = 3;
	m_M[18].columns = 3;
	m_M[19].mat = &m_V[144];		/* CalculateJ\Rtip5 */
	m_M[19].rows = 3;
	m_M[19].columns = 3;
	m_M[20].mat = &m_V[153];		/* CalculateJ\p1ref */
	m_M[20].rows = 3;
	m_M[20].columns = 1;
	m_M[21].mat = &m_V[156];		/* CalculateJ\p21 */
	m_M[21].rows = 3;
	m_M[21].columns = 1;
	m_M[22].mat = &m_V[159];		/* CalculateJ\p32 */
	m_M[22].rows = 3;
	m_M[22].columns = 1;
	m_M[23].mat = &m_V[162];		/* CalculateJ\p43 */
	m_M[23].rows = 3;
	m_M[23].columns = 1;
	m_M[24].mat = &m_V[165];		/* CalculateJ\p54 */
	m_M[24].rows = 3;
	m_M[24].columns = 1;
	m_M[25].mat = &m_V[168];		/* CalculateJ\ptip5 */
	m_M[25].rows = 3;
	m_M[25].columns = 1;
	m_M[26].mat = &m_V[171];		/* CalculateJ\Href0 */
	m_M[26].rows = 4;
	m_M[26].columns = 4;
	m_M[27].mat = &m_V[187];		/* CalculateJ\H1ref */
	m_M[27].rows = 4;
	m_M[27].columns = 4;
	m_M[28].mat = &m_V[203];		/* CalculateJ\H21 */
	m_M[28].rows = 4;
	m_M[28].columns = 4;
	m_M[29].mat = &m_V[219];		/* CalculateJ\H32 */
	m_M[29].rows = 4;
	m_M[29].columns = 4;
	m_M[30].mat = &m_V[235];		/* CalculateJ\H43 */
	m_M[30].rows = 4;
	m_M[30].columns = 4;
	m_M[31].mat = &m_V[251];		/* CalculateJ\H54 */
	m_M[31].rows = 4;
	m_M[31].columns = 4;
	m_M[32].mat = &m_V[267];		/* CalculateJ\Htip5 */
	m_M[32].rows = 4;
	m_M[32].columns = 4;
	m_M[33].mat = &m_V[283];		/* CalculateJ\H10 */
	m_M[33].rows = 4;
	m_M[33].columns = 4;
	m_M[34].mat = &m_V[299];		/* CalculateJ\H20 */
	m_M[34].rows = 4;
	m_M[34].columns = 4;
	m_M[35].mat = &m_V[315];		/* CalculateJ\H30 */
	m_M[35].rows = 4;
	m_M[35].columns = 4;
	m_M[36].mat = &m_V[331];		/* CalculateJ\H40 */
	m_M[36].rows = 4;
	m_M[36].columns = 4;
	m_M[37].mat = &m_V[347];		/* CalculateJ\H50 */
	m_M[37].rows = 4;
	m_M[37].columns = 4;
	m_M[38].mat = &m_V[363];		/* ControllableJ1\joints.e */
	m_M[38].rows = 5;
	m_M[38].columns = 1;
	m_M[39].mat = &m_V[368];		/* ControllableJ1\joints.f */
	m_M[39].rows = 5;
	m_M[39].columns = 1;
	m_M[40].mat = &m_V[373];		/* ControllableJ1\tip.f */
	m_M[40].rows = 6;
	m_M[40].columns = 1;
	m_M[41].mat = &m_V[379];		/* CtipControl1\p.e */
	m_M[41].rows = 6;
	m_M[41].columns = 1;
	m_M[42].mat = &m_V[385];		/* CtipControl1\state */
	m_M[42].rows = 4;
	m_M[42].columns = 4;
	m_M[43].mat = &m_V[402];		/* CtipControl1\omega */
	m_M[43].rows = 3;
	m_M[43].columns = 1;
	m_M[44].mat = &m_V[405];		/* CtipControl1\Wr */
	m_M[44].rows = 6;
	m_M[44].columns = 1;
	m_M[45].mat = &m_V[411];		/* CtipControl1\Wt */
	m_M[45].rows = 6;
	m_M[45].columns = 1;
	m_M[46].mat = &m_V[418];		/* OneJunction\p1.e */
	m_M[46].rows = 6;
	m_M[46].columns = 1;
	m_M[47].mat = &m_V[424];		/* VirtualPosition\output */
	m_M[47].rows = 4;
	m_M[47].columns = 4;
	m_M[48].mat = &m_V[440];		/* VirtualPosition\xyzrpy */
	m_M[48].rows = 6;
	m_M[48].columns = 1;
	m_M[49].mat = &m_V[446];		/* VirtualPosition\Rz */
	m_M[49].rows = 3;
	m_M[49].columns = 3;
	m_M[50].mat = &m_V[455];		/* VirtualPosition\Ry */
	m_M[50].rows = 3;
	m_M[50].columns = 3;
	m_M[51].mat = &m_V[464];		/* VirtualPosition\Rx */
	m_M[51].rows = 3;
	m_M[51].columns = 3;
	m_M[52].mat = &m_V[473];		/* joints.e */
	m_M[52].rows = 5;
	m_M[52].columns = 1;
	m_M[53].mat = &m_V[478];		/* joints.f */
	m_M[53].rows = 5;
	m_M[53].columns = 1;
	m_M[54].mat = &m_V[483];		/* xyzrpy */
	m_M[54].rows = 6;
	m_M[54].columns = 1;
	m_M[55].mat = &m_V[489];		/* Linkdim */
	m_M[55].rows = 3;
	m_M[55].columns = 6;
	m_M[56].mat = &m_V[507];		/* q */
	m_M[56].rows = 5;
	m_M[56].columns = 1;
	m_M[57].mat = &m_V[512];		/* output */
	m_M[57].rows = 4;
	m_M[57].columns = 4;
	m_M[58].mat = &m_U[0];		/* m_U1 */
	m_M[58].rows = 3;
	m_M[58].columns = 3;
	m_M[59].mat = &m_U[9];		/* m_U2 */
	m_M[59].rows = 3;
	m_M[59].columns = 1;
	m_M[60].mat = &m_U[12];		/* m_U3 */
	m_M[60].rows = 3;
	m_M[60].columns = 1;
	m_M[61].mat = &m_U[15];		/* m_U4 */
	m_M[61].rows = 3;
	m_M[61].columns = 3;
	m_M[62].mat = &m_U[24];		/* m_U5 */
	m_M[62].rows = 3;
	m_M[62].columns = 1;
	m_M[63].mat = &m_U[27];		/* m_U6 */
	m_M[63].rows = 3;
	m_M[63].columns = 1;
	m_M[64].mat = &m_U[30];		/* m_U7 */
	m_M[64].rows = 3;
	m_M[64].columns = 3;
	m_M[65].mat = &m_U[39];		/* m_U8 */
	m_M[65].rows = 3;
	m_M[65].columns = 1;
	m_M[66].mat = &m_U[42];		/* m_U9 */
	m_M[66].rows = 3;
	m_M[66].columns = 1;
	m_M[67].mat = &m_U[45];		/* m_U10 */
	m_M[67].rows = 3;
	m_M[67].columns = 3;
	m_M[68].mat = &m_U[54];		/* m_U11 */
	m_M[68].rows = 3;
	m_M[68].columns = 1;
	m_M[69].mat = &m_U[57];		/* m_U12 */
	m_M[69].rows = 3;
	m_M[69].columns = 1;
	m_M[70].mat = &m_U[60];		/* m_U13 */
	m_M[70].rows = 3;
	m_M[70].columns = 3;
	m_M[71].mat = &m_U[69];		/* m_U14 */
	m_M[71].rows = 3;
	m_M[71].columns = 1;
	m_M[72].mat = &m_U[72];		/* m_U15 */
	m_M[72].rows = 3;
	m_M[72].columns = 1;
	m_M[73].mat = &m_U[75];		/* m_U16 */
	m_M[73].rows = 3;
	m_M[73].columns = 3;
	m_M[74].mat = &m_U[84];		/* m_U17 */
	m_M[74].rows = 3;
	m_M[74].columns = 1;
	m_M[75].mat = &m_U[87];		/* m_U18 */
	m_M[75].rows = 6;
	m_M[75].columns = 1;
	m_M[76].mat = &m_U[93];		/* m_U19 */
	m_M[76].rows = 6;
	m_M[76].columns = 6;
	m_M[77].mat = &m_U[129];		/* m_U20 */
	m_M[77].rows = 6;
	m_M[77].columns = 1;
	m_M[78].mat = &m_U[135];		/* m_U21 */
	m_M[78].rows = 6;
	m_M[78].columns = 6;
	m_M[79].mat = &m_U[171];		/* m_U22 */
	m_M[79].rows = 6;
	m_M[79].columns = 1;
	m_M[80].mat = &m_U[177];		/* m_U23 */
	m_M[80].rows = 6;
	m_M[80].columns = 6;
	m_M[81].mat = &m_U[213];		/* m_U24 */
	m_M[81].rows = 6;
	m_M[81].columns = 1;
	m_M[82].mat = &m_U[219];		/* m_U25 */
	m_M[82].rows = 6;
	m_M[82].columns = 6;
	m_M[83].mat = &m_U[255];		/* m_U26 */
	m_M[83].rows = 6;
	m_M[83].columns = 1;
	m_M[84].mat = &m_U[261];		/* m_U27 */
	m_M[84].rows = 6;
	m_M[84].columns = 6;
	m_M[85].mat = &m_U[297];		/* m_U28 */
	m_M[85].rows = 3;
	m_M[85].columns = 3;
	m_M[86].mat = &m_U[306];		/* m_U29 */
	m_M[86].rows = 3;
	m_M[86].columns = 3;
	m_M[87].mat = &m_U[315];		/* m_U30 */
	m_M[87].rows = 3;
	m_M[87].columns = 1;
	m_M[88].mat = &m_U[318];		/* m_U31 */
	m_M[88].rows = 4;
	m_M[88].columns = 4;
	m_M[89].mat = &m_U[334];		/* m_U32 */
	m_M[89].rows = 1;
	m_M[89].columns = 1;
	m_M[90].mat = &m_U[335];		/* m_U33 */
	m_M[90].rows = 3;
	m_M[90].columns = 3;
	m_M[91].mat = &m_U[344];		/* m_U34 */
	m_M[91].rows = 1;
	m_M[91].columns = 1;
	m_M[92].mat = &m_U[345];		/* m_U35 */
	m_M[92].rows = 1;
	m_M[92].columns = 1;
	m_M[93].mat = &m_U[346];		/* m_U36 */
	m_M[93].rows = 3;
	m_M[93].columns = 1;
	m_M[94].mat = &m_U[349];		/* m_U37 */
	m_M[94].rows = 3;
	m_M[94].columns = 1;
	m_M[95].mat = &m_U[352];		/* m_U38 */
	m_M[95].rows = 3;
	m_M[95].columns = 1;
	m_M[96].mat = &m_U[355];		/* m_U39 */
	m_M[96].rows = 3;
	m_M[96].columns = 1;
	m_M[97].mat = &m_U[358];		/* m_U40 */
	m_M[97].rows = 3;
	m_M[97].columns = 1;
	m_M[98].mat = &m_U[361];		/* m_U41 */
	m_M[98].rows = 6;
	m_M[98].columns = 6;
	m_M[99].mat = &m_U[397];		/* m_U42 */
	m_M[99].rows = 6;
	m_M[99].columns = 6;
	m_M[100].mat = &m_U[433];		/* m_U43 */
	m_M[100].rows = 6;
	m_M[100].columns = 6;
	m_M[101].mat = &m_U[469];		/* m_U44 */
	m_M[101].rows = 6;
	m_M[101].columns = 1;
	m_M[102].mat = &m_U[475];		/* m_U45 */
	m_M[102].rows = 5;
	m_M[102].columns = 6;


	/* calculate initial and static equations */
	CalculateInitial ();
	CalculateStatic ();

	/* end of initialization phase */
	m_initialize = false;

	state = initialrun;
}

/* the function that calculates the submodel */
void PositionInteractionControl::Calculate (XXDouble *u, XXDouble *y /*, XXDouble t*/)
{
	/* another precessor submodel could determine the parameters of this submodel
	   and therefore the static parameter calculations need to be performed. */
	CalculateStatic ();

	switch (state)
	{
		case initialrun:	/* calculate the model for the first time */
			CopyInputsToVariables (u);
			CalculateInput ();
			CalculateDynamic();
			CalculateOutput ();
			CopyVariablesToOutputs (y);
			state = mainrun;
			break;
		case mainrun:	/* calculate the model */

			
				CopyInputsToVariables (u);
				CalculateInput ();
				myintegmethod.Step();
				CalculateOutput ();
				CopyVariablesToOutputs (y);
			break;
		case finished:
			throw std::logic_error("The simulation was finished"); 
			break;
		default:
			throw std::logic_error("The simulation state machine is inconsistent"); 
			break;
	}
}

/* the termination function for submodel */
void PositionInteractionControl::Terminate (XXDouble *u, XXDouble *y /*, XXDouble t */)
{
	/* copy the inputs */
	CopyInputsToVariables (u);

	/* calculate the final model equations */
	CalculateFinal ();

	/* set the outputs */
	CopyVariablesToOutputs (y);
}


/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void PositionInteractionControl::CalculateInitial (void)
{

}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void PositionInteractionControl::CalculateStatic (void)
{
	/* CalculateJ\Href0 = homogeneous (eye (3), [0; 0; 0]); */
	XXMatrixEye (&m_M[58]);
	m_M[59].mat[0] = 0.0;
	m_M[59].mat[1] = 0.0;
	m_M[59].mat[2] = 0.0;
	XXMatrixHomogeneous (&m_M[26], &m_M[58], &m_M[59]);

	/* CalculateJ\Rtip5 = eye (3); */
	XXMatrixEye (&m_M[19]);

	/* CalculateJ\uTr1refref[1:3] = CalculateJ\omega1; */
	m_M[9].mat[0] = m_M[4].mat[0];
	m_M[9].mat[1] = m_M[4].mat[1];
	m_M[9].mat[2] = m_M[4].mat[2];

	/* CalculateJ\uTr211[1:3] = CalculateJ\omega2; */
	m_M[10].mat[0] = m_M[5].mat[0];
	m_M[10].mat[1] = m_M[5].mat[1];
	m_M[10].mat[2] = m_M[5].mat[2];

	/* CalculateJ\uTr322[1:3] = CalculateJ\omega3; */
	m_M[11].mat[0] = m_M[6].mat[0];
	m_M[11].mat[1] = m_M[6].mat[1];
	m_M[11].mat[2] = m_M[6].mat[2];

	/* CalculateJ\uTr433[1:3] = CalculateJ\omega4; */
	m_M[12].mat[0] = m_M[7].mat[0];
	m_M[12].mat[1] = m_M[7].mat[1];
	m_M[12].mat[2] = m_M[7].mat[2];

	/* CalculateJ\uTr544[1:3] = CalculateJ\omega5; */
	m_M[13].mat[0] = m_M[8].mat[0];
	m_M[13].mat[1] = m_M[8].mat[1];
	m_M[13].mat[2] = m_M[8].mat[2];

	/* CtipControl1\Wt[1:3] = 0; */
	m_M[45].mat[0] = 0.0;
	m_M[45].mat[1] = 0.0;
	m_M[45].mat[2] = 0.0;

	/* CtipControl1\Wr[4:6] = 0; */
	m_M[44].mat[3] = 0.0;
	m_M[44].mat[4] = 0.0;
	m_M[44].mat[5] = 0.0;

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void PositionInteractionControl::CalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void PositionInteractionControl::CalculateDynamic (void)
{
	/* VirtualPosition\xyzrpy = xyzrpy; */
	XXMatrixMov (&m_M[48], &m_M[54]);

	/* CalculateJ\Linkdim = Linkdim; */
	XXMatrixMov (&m_M[2], &m_M[55]);

	/* CalculateJ\q = q; */
	XXMatrixMov (&m_M[3], &m_M[56]);

	/* CalculateJ\R1ref = [cos (CalculateJ\q[1]), -sin (CalculateJ\q[1]), 0; sin (CalculateJ\q[1]), cos (CalculateJ\q[1]), 0; 0, 0, 1]; */
	m_M[14].mat[0] = cos (m_M[3].mat[0]);
	m_M[14].mat[1] = -(sin (m_M[3].mat[0]));
	m_M[14].mat[2] = 0.0;
	m_M[14].mat[3] = sin (m_M[3].mat[0]);
	m_M[14].mat[4] = cos (m_M[3].mat[0]);
	m_M[14].mat[5] = 0.0;
	m_M[14].mat[6] = 0.0;
	m_M[14].mat[7] = 0.0;
	m_M[14].mat[8] = 1.0;

	/* CalculateJ\p1ref = CalculateJ\Linkdim[1:3,1]; */
	m_M[20].mat[0] = m_M[2].mat[0];
	m_M[20].mat[1] = m_M[2].mat[6];
	m_M[20].mat[2] = m_M[2].mat[12];

	/* CalculateJ\H1ref = homogeneous (CalculateJ\R1ref, CalculateJ\p1ref); */
	XXMatrixHomogeneous (&m_M[27], &m_M[14], &m_M[20]);

	/* CalculateJ\R21 = [cos (CalculateJ\q[2]), 0, sin (CalculateJ\q[2]); 0, 1, 0; -sin (CalculateJ\q[2]), 0, cos (CalculateJ\q[2])]; */
	m_M[15].mat[0] = cos (m_M[3].mat[1]);
	m_M[15].mat[1] = 0.0;
	m_M[15].mat[2] = sin (m_M[3].mat[1]);
	m_M[15].mat[3] = 0.0;
	m_M[15].mat[4] = 1.0;
	m_M[15].mat[5] = 0.0;
	m_M[15].mat[6] = -(sin (m_M[3].mat[1]));
	m_M[15].mat[7] = 0.0;
	m_M[15].mat[8] = cos (m_M[3].mat[1]);

	/* CalculateJ\p21 = CalculateJ\Linkdim[1:3,2]; */
	m_M[21].mat[0] = m_M[2].mat[1];
	m_M[21].mat[1] = m_M[2].mat[7];
	m_M[21].mat[2] = m_M[2].mat[13];

	/* CalculateJ\H21 = homogeneous (CalculateJ\R21, CalculateJ\p21); */
	XXMatrixHomogeneous (&m_M[28], &m_M[15], &m_M[21]);

	/* CalculateJ\R32 = [cos (CalculateJ\q[3]), 0, sin (CalculateJ\q[3]); 0, 1, 0; -sin (CalculateJ\q[3]), 0, cos (CalculateJ\q[3])]; */
	m_M[16].mat[0] = cos (m_M[3].mat[2]);
	m_M[16].mat[1] = 0.0;
	m_M[16].mat[2] = sin (m_M[3].mat[2]);
	m_M[16].mat[3] = 0.0;
	m_M[16].mat[4] = 1.0;
	m_M[16].mat[5] = 0.0;
	m_M[16].mat[6] = -(sin (m_M[3].mat[2]));
	m_M[16].mat[7] = 0.0;
	m_M[16].mat[8] = cos (m_M[3].mat[2]);

	/* CalculateJ\p32 = CalculateJ\Linkdim[1:3,3]; */
	m_M[22].mat[0] = m_M[2].mat[2];
	m_M[22].mat[1] = m_M[2].mat[8];
	m_M[22].mat[2] = m_M[2].mat[14];

	/* CalculateJ\H32 = homogeneous (CalculateJ\R32, CalculateJ\p32); */
	XXMatrixHomogeneous (&m_M[29], &m_M[16], &m_M[22]);

	/* CalculateJ\R43 = [cos (CalculateJ\q[4]), 0, sin (CalculateJ\q[4]); 0, 1, 0; -sin (CalculateJ\q[4]), 0, cos (CalculateJ\q[4])]; */
	m_M[17].mat[0] = cos (m_M[3].mat[3]);
	m_M[17].mat[1] = 0.0;
	m_M[17].mat[2] = sin (m_M[3].mat[3]);
	m_M[17].mat[3] = 0.0;
	m_M[17].mat[4] = 1.0;
	m_M[17].mat[5] = 0.0;
	m_M[17].mat[6] = -(sin (m_M[3].mat[3]));
	m_M[17].mat[7] = 0.0;
	m_M[17].mat[8] = cos (m_M[3].mat[3]);

	/* CalculateJ\p43 = CalculateJ\Linkdim[1:3,4]; */
	m_M[23].mat[0] = m_M[2].mat[3];
	m_M[23].mat[1] = m_M[2].mat[9];
	m_M[23].mat[2] = m_M[2].mat[15];

	/* CalculateJ\H43 = homogeneous (CalculateJ\R43, CalculateJ\p43); */
	XXMatrixHomogeneous (&m_M[30], &m_M[17], &m_M[23]);

	/* CalculateJ\R54 = [cos (CalculateJ\q[5]), -sin (CalculateJ\q[5]), 0; sin (CalculateJ\q[5]), cos (CalculateJ\q[5]), 0; 0, 0, 1]; */
	m_M[18].mat[0] = cos (m_M[3].mat[4]);
	m_M[18].mat[1] = -(sin (m_M[3].mat[4]));
	m_M[18].mat[2] = 0.0;
	m_M[18].mat[3] = sin (m_M[3].mat[4]);
	m_M[18].mat[4] = cos (m_M[3].mat[4]);
	m_M[18].mat[5] = 0.0;
	m_M[18].mat[6] = 0.0;
	m_M[18].mat[7] = 0.0;
	m_M[18].mat[8] = 1.0;

	/* CalculateJ\p54 = CalculateJ\Linkdim[1:3,5]; */
	m_M[24].mat[0] = m_M[2].mat[4];
	m_M[24].mat[1] = m_M[2].mat[10];
	m_M[24].mat[2] = m_M[2].mat[16];

	/* CalculateJ\H54 = homogeneous (CalculateJ\R54, CalculateJ\p54); */
	XXMatrixHomogeneous (&m_M[31], &m_M[18], &m_M[24]);

	/* CalculateJ\ptip5 = CalculateJ\Linkdim[1:3,6]; */
	m_M[25].mat[0] = m_M[2].mat[5];
	m_M[25].mat[1] = m_M[2].mat[11];
	m_M[25].mat[2] = m_M[2].mat[17];

	/* CalculateJ\Htip5 = homogeneous (CalculateJ\Rtip5, CalculateJ\ptip5); */
	XXMatrixHomogeneous (&m_M[32], &m_M[19], &m_M[25]);

	/* CalculateJ\H10 = CalculateJ\Href0 * CalculateJ\H1ref; */
	XXMatrixMul (&m_M[33], &m_M[26], &m_M[27]);

	/* CalculateJ\H20 = CalculateJ\H10 * CalculateJ\H21; */
	XXMatrixMul (&m_M[34], &m_M[33], &m_M[28]);

	/* CalculateJ\H30 = CalculateJ\H20 * CalculateJ\H32; */
	XXMatrixMul (&m_M[35], &m_M[34], &m_M[29]);

	/* CalculateJ\H40 = CalculateJ\H30 * CalculateJ\H43; */
	XXMatrixMul (&m_M[36], &m_M[35], &m_M[30]);

	/* CalculateJ\H50 = CalculateJ\H40 * CalculateJ\H54; */
	XXMatrixMul (&m_M[37], &m_M[36], &m_M[31]);

	/* CalculateJ\Htip0 = CalculateJ\H50 * CalculateJ\Htip5; */
	XXMatrixMul (&m_M[1], &m_M[37], &m_M[32]);

	/* CalculateJ\uTr1refref[4:6] = skew (CalculateJ\Linkdim[1:3,1]) * CalculateJ\omega1; */
	m_M[62].mat[0] = m_M[2].mat[0];
	m_M[62].mat[1] = m_M[2].mat[6];
	m_M[62].mat[2] = m_M[2].mat[12];
	XXMatrixSkew (&m_M[61], &m_M[62]);
	XXMatrixMul (&m_M[60], &m_M[61], &m_M[4]);
	m_M[9].mat[3] = m_M[60].mat[0];
	m_M[9].mat[4] = m_M[60].mat[1];
	m_M[9].mat[5] = m_M[60].mat[2];

	/* CalculateJ\uTr211[4:6] = skew (CalculateJ\Linkdim[1:3,2]) * CalculateJ\omega2; */
	m_M[65].mat[0] = m_M[2].mat[1];
	m_M[65].mat[1] = m_M[2].mat[7];
	m_M[65].mat[2] = m_M[2].mat[13];
	XXMatrixSkew (&m_M[64], &m_M[65]);
	XXMatrixMul (&m_M[63], &m_M[64], &m_M[5]);
	m_M[10].mat[3] = m_M[63].mat[0];
	m_M[10].mat[4] = m_M[63].mat[1];
	m_M[10].mat[5] = m_M[63].mat[2];

	/* CalculateJ\uTr322[4:6] = skew (CalculateJ\Linkdim[1:3,3]) * CalculateJ\omega3; */
	m_M[68].mat[0] = m_M[2].mat[2];
	m_M[68].mat[1] = m_M[2].mat[8];
	m_M[68].mat[2] = m_M[2].mat[14];
	XXMatrixSkew (&m_M[67], &m_M[68]);
	XXMatrixMul (&m_M[66], &m_M[67], &m_M[6]);
	m_M[11].mat[3] = m_M[66].mat[0];
	m_M[11].mat[4] = m_M[66].mat[1];
	m_M[11].mat[5] = m_M[66].mat[2];

	/* CalculateJ\uTr433[4:6] = skew (CalculateJ\Linkdim[1:3,4]) * CalculateJ\omega4; */
	m_M[71].mat[0] = m_M[2].mat[3];
	m_M[71].mat[1] = m_M[2].mat[9];
	m_M[71].mat[2] = m_M[2].mat[15];
	XXMatrixSkew (&m_M[70], &m_M[71]);
	XXMatrixMul (&m_M[69], &m_M[70], &m_M[7]);
	m_M[12].mat[3] = m_M[69].mat[0];
	m_M[12].mat[4] = m_M[69].mat[1];
	m_M[12].mat[5] = m_M[69].mat[2];

	/* CalculateJ\uTr544[4:6] = skew (CalculateJ\Linkdim[1:3,5]) * CalculateJ\omega5; */
	m_M[74].mat[0] = m_M[2].mat[4];
	m_M[74].mat[1] = m_M[2].mat[10];
	m_M[74].mat[2] = m_M[2].mat[16];
	XXMatrixSkew (&m_M[73], &m_M[74]);
	XXMatrixMul (&m_M[72], &m_M[73], &m_M[8]);
	m_M[13].mat[3] = m_M[72].mat[0];
	m_M[13].mat[4] = m_M[72].mat[1];
	m_M[13].mat[5] = m_M[72].mat[2];

	/* CalculateJ\controllableJ[1:6,1] = Adjoint (CalculateJ\Href0) * CalculateJ\uTr1refref; */
	XXMatrixAdjoint (&m_M[76], &m_M[26]);
	XXMatrixMul (&m_M[75], &m_M[76], &m_M[9]);
	m_M[0].mat[0] = m_M[75].mat[0];
	m_M[0].mat[5] = m_M[75].mat[1];
	m_M[0].mat[10] = m_M[75].mat[2];
	m_M[0].mat[15] = m_M[75].mat[3];
	m_M[0].mat[20] = m_M[75].mat[4];
	m_M[0].mat[25] = m_M[75].mat[5];

	/* CalculateJ\controllableJ[1:6,2] = Adjoint (CalculateJ\H10) * CalculateJ\uTr211; */
	XXMatrixAdjoint (&m_M[78], &m_M[33]);
	XXMatrixMul (&m_M[77], &m_M[78], &m_M[10]);
	m_M[0].mat[1] = m_M[77].mat[0];
	m_M[0].mat[6] = m_M[77].mat[1];
	m_M[0].mat[11] = m_M[77].mat[2];
	m_M[0].mat[16] = m_M[77].mat[3];
	m_M[0].mat[21] = m_M[77].mat[4];
	m_M[0].mat[26] = m_M[77].mat[5];

	/* CalculateJ\controllableJ[1:6,3] = Adjoint (CalculateJ\H20) * CalculateJ\uTr322; */
	XXMatrixAdjoint (&m_M[80], &m_M[34]);
	XXMatrixMul (&m_M[79], &m_M[80], &m_M[11]);
	m_M[0].mat[2] = m_M[79].mat[0];
	m_M[0].mat[7] = m_M[79].mat[1];
	m_M[0].mat[12] = m_M[79].mat[2];
	m_M[0].mat[17] = m_M[79].mat[3];
	m_M[0].mat[22] = m_M[79].mat[4];
	m_M[0].mat[27] = m_M[79].mat[5];

	/* CalculateJ\controllableJ[1:6,4] = Adjoint (CalculateJ\H30) * CalculateJ\uTr433; */
	XXMatrixAdjoint (&m_M[82], &m_M[35]);
	XXMatrixMul (&m_M[81], &m_M[82], &m_M[12]);
	m_M[0].mat[3] = m_M[81].mat[0];
	m_M[0].mat[8] = m_M[81].mat[1];
	m_M[0].mat[13] = m_M[81].mat[2];
	m_M[0].mat[18] = m_M[81].mat[3];
	m_M[0].mat[23] = m_M[81].mat[4];
	m_M[0].mat[28] = m_M[81].mat[5];

	/* CalculateJ\controllableJ[1:6,5] = Adjoint (CalculateJ\H40) * CalculateJ\uTr544; */
	XXMatrixAdjoint (&m_M[84], &m_M[36]);
	XXMatrixMul (&m_M[83], &m_M[84], &m_M[13]);
	m_M[0].mat[4] = m_M[83].mat[0];
	m_M[0].mat[9] = m_M[83].mat[1];
	m_M[0].mat[14] = m_M[83].mat[2];
	m_M[0].mat[19] = m_M[83].mat[3];
	m_M[0].mat[24] = m_M[83].mat[4];
	m_M[0].mat[29] = m_M[83].mat[5];

	/* VirtualPosition\Rz = [cos (VirtualPosition\xyzrpy[5]), sin (VirtualPosition\xyzrpy[5]), 0; -sin (VirtualPosition\xyzrpy[5]), cos (VirtualPosition\xyzrpy[5]), 0; 0, 0, 1]; */
	m_M[49].mat[0] = cos (m_M[48].mat[4]);
	m_M[49].mat[1] = sin (m_M[48].mat[4]);
	m_M[49].mat[2] = 0.0;
	m_M[49].mat[3] = -(sin (m_M[48].mat[4]));
	m_M[49].mat[4] = cos (m_M[48].mat[4]);
	m_M[49].mat[5] = 0.0;
	m_M[49].mat[6] = 0.0;
	m_M[49].mat[7] = 0.0;
	m_M[49].mat[8] = 1.0;

	/* VirtualPosition\Ry = [cos (VirtualPosition\xyzrpy[4]), 0, -sin (VirtualPosition\xyzrpy[4]); 0, 1, 0; sin (VirtualPosition\xyzrpy[4]), 0, cos (VirtualPosition\xyzrpy[4])]; */
	m_M[50].mat[0] = cos (m_M[48].mat[3]);
	m_M[50].mat[1] = 0.0;
	m_M[50].mat[2] = -(sin (m_M[48].mat[3]));
	m_M[50].mat[3] = 0.0;
	m_M[50].mat[4] = 1.0;
	m_M[50].mat[5] = 0.0;
	m_M[50].mat[6] = sin (m_M[48].mat[3]);
	m_M[50].mat[7] = 0.0;
	m_M[50].mat[8] = cos (m_M[48].mat[3]);

	/* VirtualPosition\Rx = [1, 0, 0; 0, cos (VirtualPosition\xyzrpy[6]), sin (VirtualPosition\xyzrpy[6]); 0, -sin (VirtualPosition\xyzrpy[6]), cos (VirtualPosition\xyzrpy[6])]; */
	m_M[51].mat[0] = 1.0;
	m_M[51].mat[1] = 0.0;
	m_M[51].mat[2] = 0.0;
	m_M[51].mat[3] = 0.0;
	m_M[51].mat[4] = cos (m_M[48].mat[5]);
	m_M[51].mat[5] = sin (m_M[48].mat[5]);
	m_M[51].mat[6] = 0.0;
	m_M[51].mat[7] = -(sin (m_M[48].mat[5]));
	m_M[51].mat[8] = cos (m_M[48].mat[5]);

	/* VirtualPosition\output = homogeneous ((VirtualPosition\Rx * VirtualPosition\Ry) * VirtualPosition\Rz, VirtualPosition\xyzrpy[1:3]); */
	XXMatrixMul (&m_M[86], &m_M[51], &m_M[50]);
	XXMatrixMul (&m_M[85], &m_M[86], &m_M[49]);
	m_M[87].mat[0] = m_M[48].mat[0];
	m_M[87].mat[1] = m_M[48].mat[1];
	m_M[87].mat[2] = m_M[48].mat[2];
	XXMatrixHomogeneous (&m_M[47], &m_M[85], &m_M[87]);

	/* output = CalculateJ\Htip0; */
	XXMatrixMov (&m_M[57], &m_M[1]);

	/* CtipControl1\state = inverse (VirtualPosition\output) * CalculateJ\Htip0; */
	XXMatrixInverse (&m_M[88], &m_M[47], m_workarray);
	XXMatrixMul (&m_M[42], &m_M[88], &m_M[1]);

	/* CtipControl1\temp = (trace (CtipControl1\state[1:3,1:3]) - 1) / 2; */
	m_M[90].mat[0] = m_M[42].mat[0];
	m_M[90].mat[1] = m_M[42].mat[1];
	m_M[90].mat[2] = m_M[42].mat[2];
	m_M[90].mat[3] = m_M[42].mat[4];
	m_M[90].mat[4] = m_M[42].mat[5];
	m_M[90].mat[5] = m_M[42].mat[6];
	m_M[90].mat[6] = m_M[42].mat[8];
	m_M[90].mat[7] = m_M[42].mat[9];
	m_M[90].mat[8] = m_M[42].mat[10];
	m_M[89].mat[0] = XXMatrixTrace (&m_M[90]);
	m_V[417] = (XXMatrixTrace (&m_M[90]) - 1.0) / 2.0;

	/* if (CtipControl1\temp < -1) */
	if (m_V[417] < -1.0)
	{
		/* CtipControl1\temp = -1; */
		m_V[417] = -1.0;
	}

	/* if (CtipControl1\temp > 1) */
	if (m_V[417] > 1.0)
	{
		/* CtipControl1\temp = 1; */
		m_V[417] = 1.0;
	}

	/* CtipControl1\theta = arccos (CtipControl1\temp); */
	m_V[401] = acos (m_V[417]);

	/* if (CtipControl1\theta == 0) */
	if (m_V[401] == 0.0)
	{
		/* CtipControl1\omega = 0; */
		XXMatrixScalarMov (&m_M[43], 0.0);
	}
	else
	{
		/* CtipControl1\omega = (1 / (2 * sin (CtipControl1\theta))) * [CtipControl1\state[3,2] - CtipControl1\state[2,3]; CtipControl1\state[1,3] - CtipControl1\state[3,1]; CtipControl1\state[2,1] - CtipControl1\state[1,2]]; */
		m_M[93].mat[0] = m_M[42].mat[9] - m_M[42].mat[6];
		m_M[93].mat[1] = m_M[42].mat[2] - m_M[42].mat[8];
		m_M[93].mat[2] = m_M[42].mat[4] - m_M[42].mat[1];
		XXScalarMatrixMul (&m_M[43], (1.0 / (2.0 * sin (m_V[401]))), &m_M[93]);
	}

	/* CtipControl1\Wt[4:6] = CtipControl1\state[1:3,4] / CtipControl1\CtipControl; */
	m_M[95].mat[0] = m_M[42].mat[3];
	m_M[95].mat[1] = m_M[42].mat[7];
	m_M[95].mat[2] = m_M[42].mat[11];
	XXMatrixScalarDiv (&m_M[94], &m_M[95], m_P[0]);
	m_M[45].mat[3] = m_M[94].mat[0];
	m_M[45].mat[4] = m_M[94].mat[1];
	m_M[45].mat[5] = m_M[94].mat[2];

	/* CtipControl1\Wr[1:3] = (CtipControl1\theta * CtipControl1\omega) / (CtipControl1\CtipControl); */
	XXScalarMatrixMul (&m_M[97], m_V[401], &m_M[43]);
	XXMatrixScalarDiv (&m_M[96], &m_M[97], (m_P[0]));
	m_M[44].mat[0] = m_M[96].mat[0];
	m_M[44].mat[1] = m_M[96].mat[1];
	m_M[44].mat[2] = m_M[96].mat[2];

	/* CtipControl1\p.e = inverse (transpose (Adjoint (VirtualPosition\output))) * (CtipControl1\Wt + CtipControl1\Wr); */
	XXMatrixAdjoint (&m_M[100], &m_M[47]);
	XXMatrixTranspose (&m_M[99], &m_M[100]);
	XXMatrixInverse (&m_M[98], &m_M[99], m_workarray);
	XXMatrixAdd (&m_M[101], &m_M[45], &m_M[44]);
	XXMatrixMul (&m_M[41], &m_M[98], &m_M[101]);

	/* OneJunction\p1.e = -CtipControl1\p.e; */
	XXMatrixInv (&m_M[46], &m_M[41]);

	/* ControllableJ1\joints.e = transpose (CalculateJ\controllableJ) * OneJunction\p1.e; */
	XXMatrixTranspose (&m_M[102], &m_M[0]);
	XXMatrixMul (&m_M[38], &m_M[102], &m_M[46]);

	/* joints.e = ControllableJ1\joints.e; */
	XXMatrixMov (&m_M[52], &m_M[38]);

}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void PositionInteractionControl::CalculateOutput (void)
{
	/* ControllableJ1\joints.f = joints.f; */
	XXMatrixMov (&m_M[39], &m_M[53]);

	/* ControllableJ1\tip.f = CalculateJ\controllableJ * ControllableJ1\joints.f; */
	XXMatrixMul (&m_M[40], &m_M[0], &m_M[39]);

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void PositionInteractionControl::CalculateFinal (void)
{

}


